version: 2

updates:
  - package-ecosystem: gomod
    directory: /Atlas_Core
    schedule:
      interval: weekly
    groups:
      go-modules-minor-patch:
        update-types:
          - minor
          - patch
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /Atlas_Core/docker
    schedule:
      interval: weekly
    groups:
      docker-images-minor-patch:
        update-types:
          - minor
          - patch
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions-minor-patch:
        update-types:
          - minor
          - patch
        patterns:
          - "*"
    open-pull-requests-limit: 5
