// Code generated by scripts/generate-package-metadata.mjs; DO NOT EDIT.

export const PACKAGE_NAME = "@the-drunken-coder/atlas-sdk" as const;
export const PACKAGE_BIN = {"atlas":"./dist/packages/sdk/src/cli.js"} as const;
