package actions

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	commandcatalog "github.com/the-drunken-coder/atlas/atlas_core/command_catalog"
	"github.com/the-drunken-coder/atlas/atlas_core/internal/models"
)

func isCommandTask(components map[string]interface{}) bool {
	if components == nil {
		return false
	}
	_, ok := components["command"]
	return ok
}

func (a *TaskActions) prepareCommandTask(params CreateTaskParams) (CreateTaskParams, string, error) {
	if strings.TrimSpace(params.TaskID) != "" {
		return params, "", NewValidationError("command task_id must be generated by Core")
	}
	if params.EntityID == nil || strings.TrimSpace(*params.EntityID) == "" {
		return params, "", NewValidationError("command tasks require entity_id")
	}
	entityID := SanitizeID(*params.EntityID)
	if err := ValidateEntityID(entityID); err != nil {
		return params, "", err
	}
	commandID, err := commandIDFromComponents(params.Components)
	if err != nil {
		return params, "", err
	}
	catalog, err := commandcatalog.Default()
	if err != nil {
		return params, "", fmt.Errorf("failed to load command catalog: %w", err)
	}
	command, ok := commandcatalog.Command(catalog, commandID)
	if !ok {
		return params, "", NewValidationError("unsupported command id")
	}
	coerced, err := commandcatalog.CoerceParameters(command, params.Components["parameters"])
	if err != nil {
		return params, "", NewValidationError(err.Error())
	}
	params.TaskID = "command-" + uuid.NewString()
	params.Status = "pending"
	params.EntityID = &entityID
	params.Components = cloneMap(params.Components)
	params.Components["command"] = map[string]interface{}{"type": commandID, "id": commandID}
	params.Components["parameters"] = coerced
	return params, commandID, nil
}

func getCommandTargetEntity(ctx context.Context, tx pgx.Tx, entityID string) (*models.Entity, error) {
	var entity models.Entity
	err := tx.QueryRow(ctx, `
		SELECT entity_id, type, subtype, alias, json, created_at, updated_at, version
		FROM entities WHERE entity_id = $1
		FOR UPDATE
	`, entityID).Scan(
		&entity.EntityID, &entity.Type, &entity.Subtype, &entity.Alias,
		&entity.JSON, &entity.CreatedAt, &entity.UpdatedAt, &entity.Version,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, NewEntityNotFoundError(entityID)
		}
		return nil, fmt.Errorf("failed to load command target entity: %w", err)
	}
	return &entity, nil
}

func commandIDFromComponents(components map[string]interface{}) (string, error) {
	command, ok := components["command"].(map[string]interface{})
	if !ok {
		return "", NewValidationError("command component must be an object")
	}
	id, _ := command["id"].(string)
	typ, _ := command["type"].(string)
	id = strings.TrimSpace(id)
	typ = strings.TrimSpace(typ)
	if id == "" {
		id = typ
	}
	if typ == "" {
		typ = id
	}
	if id == "" || typ == "" {
		return "", NewValidationError("command id is required")
	}
	if id != typ {
		return "", NewValidationError("command id and type must match")
	}
	return id, nil
}

func entitySupportsCommand(entity *models.Entity, commandID string) error {
	if entity.Type != "asset" {
		return NewValidationError("only asset entities can receive commands")
	}
	components := entity.GetComponents()
	taskCatalog, ok := components["task_catalog"].(map[string]interface{})
	if !ok {
		return NewValidationError("entity does not advertise command support")
	}
	supported, ok := taskCatalog["supported_tasks"].([]interface{})
	if !ok {
		return NewValidationError("entity does not advertise command support")
	}
	for _, value := range supported {
		if value == commandID {
			return nil
		}
	}
	return NewValidationError("entity does not support command")
}

func cloneMap(input map[string]interface{}) map[string]interface{} {
	out := make(map[string]interface{}, len(input))
	for key, value := range input {
		out[key] = value
	}
	return out
}
