name: ${ATLAS_CORE_PROJECT:-atlas_core_production}

services:
  minio:
    extends:
      file: docker-compose.yml
      service: minio

volumes:
  minio_data:
    external: true
    name: ${ATLAS_CORE_PROJECT:-atlas_core_production}_minio_data

networks:
  atlas_core_network:
    driver: bridge
