package artifacts

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	protocolvalidator "github.com/the-drunken-coder/atlas/atlas_protocol/validator"
)

const commandCatalogDirectory = "commands"
const taskingFixtureCatalogPath = "conformance/tasking/fixtures/catalog.json"

func buildCommandCatalog(root string, bundle schemaBundle) ([]byte, error) {
	commands, err := loadCommandDefinitions(root, commandCatalogDirectory)
	if err != nil {
		return nil, err
	}
	if errors := protocolvalidator.ValidateCommandCatalog(commands); len(errors) > 0 {
		return nil, fmt.Errorf("validate command catalog: %s", strings.Join(errors, "; "))
	}
	if err := validateCommandSchemaReferences(bundle, commands); err != nil {
		return nil, err
	}
	sort.Slice(commands, func(i, j int) bool {
		return commands[i]["command"].(string) < commands[j]["command"].(string)
	})
	data, err := json.MarshalIndent(commands, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal command catalog: %w", err)
	}
	return append(data, '\n'), nil
}

func goCommandCatalogSource(catalog []byte) ([]byte, error) {
	source := fmt.Sprintf(`// Code generated by atlas_protocol/tools/generate; DO NOT EDIT.

package atlasprotocol

// CommandCatalogJSON is the exact generated production Command Catalog.
const CommandCatalogJSON = %q
`, string(catalog))
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("format generated Go command catalog: %w", err)
	}
	return formatted, nil
}

func validateTaskingFixtureCatalog(root string, bundle schemaBundle) error {
	path := filepath.Join(root, filepath.FromSlash(taskingFixtureCatalogPath))
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	var commands []map[string]any
	if err := json.Unmarshal(data, &commands); err != nil {
		return fmt.Errorf("decode %s: %w", taskingFixtureCatalogPath, err)
	}
	if len(commands) == 0 {
		return fmt.Errorf("%s must contain fixture Commands", taskingFixtureCatalogPath)
	}
	if errors := protocolvalidator.ValidateCommandCatalog(commands); len(errors) > 0 {
		return fmt.Errorf("validate %s: %s", taskingFixtureCatalogPath, strings.Join(errors, "; "))
	}
	return validateCommandSchemaReferences(bundle, commands)
}

func loadCommandDefinitions(root, directory string) ([]map[string]any, error) {
	path := filepath.Join(root, filepath.FromSlash(directory))
	entries, err := os.ReadDir(path)
	if err != nil {
		return nil, fmt.Errorf("read command directory %s: %w", directory, err)
	}

	var commands []map[string]any
	seen := make(map[string]string)
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".json" {
			continue
		}
		namespace := strings.TrimSuffix(entry.Name(), ".json")
		if !validCommandNamespace(namespace) {
			return nil, fmt.Errorf("command file %s must use a lowercase snake-case namespace", entry.Name())
		}
		filePath := filepath.Join(path, entry.Name())
		data, err := os.ReadFile(filePath)
		if err != nil {
			return nil, err
		}
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.UseNumber()
		var definitions []map[string]any
		if err := decoder.Decode(&definitions); err != nil {
			return nil, fmt.Errorf("decode %s: %w", displayPath(root, filePath), err)
		}
		var trailing any
		if err := decoder.Decode(&trailing); err != io.EOF {
			if err == nil {
				return nil, fmt.Errorf("decode %s: multiple JSON values", displayPath(root, filePath))
			}
			return nil, fmt.Errorf("decode %s: trailing content: %w", displayPath(root, filePath), err)
		}
		if len(definitions) == 0 {
			return nil, fmt.Errorf("%s is empty; remove it until the namespace has a Command", displayPath(root, filePath))
		}
		for _, definition := range definitions {
			command, _ := definition["command"].(string)
			prefix, _, _ := strings.Cut(command, ".")
			if command != "" && prefix != namespace {
				return nil, fmt.Errorf("%s command %q does not use namespace %q", displayPath(root, filePath), command, namespace)
			}
			if previous, duplicate := seen[command]; duplicate && command != "" {
				return nil, fmt.Errorf("command %q is duplicated in %s and %s", command, previous, displayPath(root, filePath))
			}
			seen[command] = displayPath(root, filePath)
			commands = append(commands, definition)
		}
	}
	if commands == nil {
		commands = []map[string]any{}
	}
	return commands, nil
}

func validCommandNamespace(value string) bool {
	if value == "" || value[0] < 'a' || value[0] > 'z' {
		return false
	}
	for _, char := range value {
		if (char >= 'a' && char <= 'z') || (char >= '0' && char <= '9') || char == '_' {
			continue
		}
		return false
	}
	return true
}

func validateCommandSchemaReferences(bundle schemaBundle, commands []map[string]any) error {
	defs, err := schemaDefs(bundle)
	if err != nil {
		return err
	}
	for _, command := range commands {
		name, _ := command["command"].(string)
		for _, field := range []string{"input_schema", "output_schema"} {
			reference, present := command[field].(string)
			if !present {
				continue
			}
			definition := reference[strings.LastIndex(reference, ".")+1:]
			if _, ok := defs[definition]; !ok {
				return fmt.Errorf("command %q %s references missing Protocol schema %q", name, field, reference)
			}
		}
	}
	return nil
}
