package artifacts

import "strings"

type goValidatorFunction struct {
	name   string
	params string
	args   string
}

var goValidatorFunctions = []goValidatorFunction{
	{name: "ValidateEntityBlob", params: "value any", args: "value"},
	{name: "ValidateTaskBlob", params: "value any", args: "value"},
	{name: "ValidateObjectBlob", params: "value any", args: "value"},
	{name: "ValidateEntityResource", params: "value any", args: "value"},
	{name: "ValidateTaskResource", params: "value any", args: "value"},
	{name: "ValidateObjectResource", params: "value any", args: "value"},
	{name: "ValidateFeedEvent", params: "value any", args: "value"},
	{name: "ValidateFeedAuthMessage", params: "value any", args: "value"},
	{name: "ValidateFeedSubscribeMessage", params: "value any", args: "value"},
	{name: "ValidateFeedUnsubscribeMessage", params: "value any", args: "value"},
	{name: "ValidateFeedClientMessage", params: "value any", args: "value"},
	{name: "ValidateFeedHandshakeMessage", params: "value any", args: "value"},
	{name: "ValidateEntityComponents", params: "value any", args: "value"},
	{name: "ValidateTaskComponents", params: "value any", args: "value"},
	{name: "ValidateCommandComponent", params: "value any", args: "value"},
	{name: "ValidateTaskParametersComponent", params: "value any, fieldPrefix string", args: "value, fieldPrefix"},
	{name: "ValidateTaskProgressComponent", params: "value any", args: "value"},
	{name: "ValidateTaskCatalogComponent", params: "value any", args: "value"},
	{name: "ValidateMediaRefsComponent", params: "value any", args: "value"},
	{name: "ValidateMilViewComponent", params: "value any", args: "value"},
	{name: "ValidateHealthComponent", params: "value any", args: "value"},
	{name: "ValidateSensorRefsComponent", params: "value any", args: "value"},
	{name: "ValidateCommunicationsComponent", params: "value any", args: "value"},
	{name: "ValidateTaskQueueComponent", params: "value any", args: "value"},
	{name: "ValidateStatusComponent", params: "value any", args: "value"},
	{name: "ValidateHeartbeatComponent", params: "value any", args: "value"},
	{name: "ValidateTelemetryComponent", params: "value any", args: "value"},
	{name: "ValidateGeometryComponent", params: "value any", args: "value"},
}

func goValidatorsSource() []byte {
	var builder strings.Builder
	builder.WriteString("// Code generated by go run ./tools/generate; DO NOT EDIT.\n\n")
	builder.WriteString("package atlasprotocol\n\n")
	builder.WriteString("import \"github.com/the-drunken-coder/atlas/atlas_protocol/validator\"\n\n")
	for i, fn := range goValidatorFunctions {
		if i > 0 {
			builder.WriteString("\n")
		}
		builder.WriteString("func ")
		builder.WriteString(fn.name)
		builder.WriteString("(")
		builder.WriteString(fn.params)
		builder.WriteString(") []string {\n\treturn validator.")
		builder.WriteString(fn.name)
		builder.WriteString("(")
		builder.WriteString(fn.args)
		builder.WriteString(")\n}\n")
	}
	return formatGeneratedGoSource(builder.String())
}
