package artifacts

import (
	"encoding/json"
	"fmt"
	"reflect"
	"regexp"
	"strings"
)

var safeProtocolRevisionPattern = regexp.MustCompile(`^[A-Za-z0-9._:-]+$`)

func markGeneratedJSONSchema(schema []byte, revision string) ([]byte, error) {
	revision, err := validateProtocolRevision(revision)
	if err != nil {
		return nil, err
	}
	var root map[string]any
	if err := json.Unmarshal(schema, &root); err != nil {
		return nil, err
	}
	root["$comment"] = "Code generated by go run ./tools/generate; DO NOT EDIT."
	root["x-atlas-protocol-revision"] = revision
	patchGeneratedJSONSchema(root)

	out, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(out, '\n'), nil
}

func validateProtocolRevision(revision string) (string, error) {
	revision = strings.TrimSpace(revision)
	if revision == "" {
		return "", fmt.Errorf("invalid protocol revision: empty")
	}
	if !safeProtocolRevisionPattern.MatchString(revision) {
		return "", fmt.Errorf("invalid protocol revision %q", revision)
	}
	return revision, nil
}

func hydrateEntityComponentDefs(entitySchema []byte, componentSchemas ...[]byte) ([]byte, error) {
	var entityRoot map[string]any
	if err := json.Unmarshal(entitySchema, &entityRoot); err != nil {
		return nil, fmt.Errorf("parse entity schema: %w", err)
	}
	entityDefs, err := schemaDefs(entityRoot, "entity schema")
	if err != nil {
		return nil, err
	}

	for _, componentSchema := range componentSchemas {
		var componentRoot map[string]any
		if err := json.Unmarshal(componentSchema, &componentRoot); err != nil {
			return nil, fmt.Errorf("parse component schema: %w", err)
		}
		componentDefs, err := schemaDefs(componentRoot, "component schema")
		if err != nil {
			return nil, err
		}

		for key, value := range componentDefs {
			existing, exists := entityDefs[key]
			if !exists {
				entityDefs[key] = value
				continue
			}
			if isSelfRefDef(key, existing) {
				if isSelfRefDef(key, value) {
					return nil, fmt.Errorf("component schema definition %s is still self-referential", key)
				}
				entityDefs[key] = value
				continue
			}
			if !reflect.DeepEqual(existing, value) {
				return nil, fmt.Errorf("conflicting JSON schema definition %s", key)
			}
		}
	}

	patchGeneratedJSONSchema(entityRoot)
	out, err := json.MarshalIndent(entityRoot, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(out, '\n'), nil
}

func schemaDefs(root map[string]any, name string) (map[string]any, error) {
	defs, ok := root["$defs"].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("%s has no $defs object", name)
	}
	return defs, nil
}

func isSelfRefDef(key string, value any) bool {
	node, ok := value.(map[string]any)
	if !ok || len(node) != 1 {
		return false
	}
	ref, ok := node["$ref"].(string)
	if !ok {
		return false
	}
	return ref == "#/$defs/%23"+strings.TrimPrefix(key, "#")
}

func patchGeneratedJSONSchema(root map[string]any) {
	normalizeIntegerAllOf(root)
	normalizeArrayLengthKeywords(root)
	normalizeWildcardPatternProperties(root)
	injectMinProperties(root)
}

func normalizeIntegerAllOf(value any) {
	switch node := value.(type) {
	case map[string]any:
		if simplified, ok := simplifiedIntegerAllOf(node["allOf"]); ok {
			delete(node, "allOf")
			for key, child := range simplified {
				node[key] = child
			}
		}
		for _, child := range node {
			normalizeIntegerAllOf(child)
		}
	case []any:
		for _, child := range node {
			normalizeIntegerAllOf(child)
		}
	}
}

func simplifiedIntegerAllOf(value any) (map[string]any, bool) {
	items, ok := value.([]any)
	if !ok {
		return nil, false
	}

	var integerSchema map[string]any
	for _, item := range items {
		schema, ok := item.(map[string]any)
		if !ok {
			return nil, false
		}
		switch schemaType(schema) {
		case "number":
			if len(schema) != 1 {
				return nil, false
			}
		case "integer":
			if integerSchema != nil {
				return nil, false
			}
			integerSchema = schema
		default:
			return nil, false
		}
	}
	if integerSchema == nil {
		return nil, false
	}
	out := make(map[string]any, len(integerSchema))
	for key, child := range integerSchema {
		out[key] = child
	}
	return out, true
}

func normalizeWildcardPatternProperties(value any) {
	switch node := value.(type) {
	case map[string]any:
		if patternProperties, ok := node["patternProperties"].(map[string]any); ok && len(patternProperties) == 1 {
			if wildcard, exists := patternProperties[""]; exists {
				node["additionalProperties"] = wildcard
				delete(node, "patternProperties")
			}
		}
		for _, child := range node {
			normalizeWildcardPatternProperties(child)
		}
	case []any:
		for _, child := range node {
			normalizeWildcardPatternProperties(child)
		}
	}
}

func normalizeArrayLengthKeywords(value any) {
	switch node := value.(type) {
	case map[string]any:
		if isArraySchema(node) {
			if minLength, ok := node["minLength"]; ok {
				if _, exists := node["minItems"]; !exists {
					node["minItems"] = minLength
				}
				delete(node, "minLength")
			}
			if maxLength, ok := node["maxLength"]; ok {
				if _, exists := node["maxItems"]; !exists {
					node["maxItems"] = maxLength
				}
				delete(node, "maxLength")
			}
		}
		for _, child := range node {
			normalizeArrayLengthKeywords(child)
		}
	case []any:
		for _, child := range node {
			normalizeArrayLengthKeywords(child)
		}
	}
}

func isArraySchema(node map[string]any) bool {
	if typ, ok := node["type"].(string); ok && typ == "array" {
		return true
	}
	if _, ok := node["items"]; ok {
		return true
	}
	if _, ok := node["prefixItems"]; ok {
		return true
	}
	return false
}

func injectMinProperties(value any) {
	switch node := value.(type) {
	case map[string]any:
		if isObjectReferenceSchema(node) || isAtlasGeometrySchema(node) {
			if _, exists := node["minProperties"]; !exists {
				node["minProperties"] = 1
			}
		}
		if isAtlasGeometrySchema(node) {
			injectAtlasGeometryDependencies(node)
		}
		for _, child := range node {
			injectMinProperties(child)
		}
	case []any:
		for _, child := range node {
			injectMinProperties(child)
		}
	}
}

func isObjectReferenceSchema(node map[string]any) bool {
	props, ok := node["properties"].(map[string]any)
	if !ok {
		return false
	}
	return schemaType(node) == "object" && props["entity_id"] != nil && props["task_id"] != nil
}

func isAtlasGeometrySchema(node map[string]any) bool {
	props, ok := node["properties"].(map[string]any)
	if !ok {
		return false
	}
	return schemaType(node) == "object" &&
		props["point_lat"] != nil &&
		props["point_lng"] != nil &&
		props["radius_m"] != nil &&
		props["line"] != nil &&
		props["polygon"] != nil
}

func injectAtlasGeometryDependencies(node map[string]any) {
	if _, exists := node["dependentRequired"]; exists {
		return
	}
	node["dependentRequired"] = map[string]any{
		"point_lat": []any{"point_lng"},
		"point_lng": []any{"point_lat"},
		"radius_m":  []any{"point_lat", "point_lng"},
	}
}

func schemaType(node map[string]any) string {
	typ, _ := node["type"].(string)
	return typ
}
