package artifacts

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func protocolRevision(root string) (string, error) {
	path := filepath.Join(root, filepath.FromSlash(schemaBundlePath))
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}

	hash := sha256.New()
	hash.Write([]byte(schemaBundlePath))
	hash.Write([]byte{0})
	hash.Write(data)
	hash.Write([]byte{0})
	return "sha256:" + hex.EncodeToString(hash.Sum(nil)), nil
}

func revisionTextSource(revision string) []byte {
	return []byte(revision + "\n")
}

func goRevisionSource(revision string) ([]byte, error) {
	var builder strings.Builder
	builder.WriteString("// Code generated by go run ./tools/generate; DO NOT EDIT.\n\n")
	builder.WriteString("package atlasprotocol\n\n")
	builder.WriteString("// ProtocolRevision identifies the protocol JSON Schema source used to generate this package.\n")
	builder.WriteString("const ProtocolRevision = ")
	_, _ = fmt.Fprintf(&builder, "%q", revision)
	builder.WriteString("\n")
	return formatGeneratedGoSource(builder.String())
}
