package artifacts

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func protocolRevision(root string) (string, error) {
	var files []string
	for _, base := range []string{"cue.mod", "schema"} {
		dir := filepath.Join(root, base)
		err := filepath.WalkDir(dir, func(path string, entry fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if entry.IsDir() {
				return nil
			}
			if filepath.Ext(path) != ".cue" {
				return nil
			}
			files = append(files, path)
			return nil
		})
		if err != nil {
			return "", err
		}
	}
	sort.Strings(files)
	if len(files) == 0 {
		return "", fmt.Errorf("no CUE protocol source files found")
	}

	hash := sha256.New()
	for _, path := range files {
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return "", err
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return "", err
		}
		hash.Write([]byte(filepath.ToSlash(rel)))
		hash.Write([]byte{0})
		hash.Write(data)
		hash.Write([]byte{0})
	}
	return "sha256:" + hex.EncodeToString(hash.Sum(nil)), nil
}

func revisionTextSource(revision string) []byte {
	return []byte(revision + "\n")
}

func goRevisionSource(revision string) []byte {
	var builder strings.Builder
	builder.WriteString("// Code generated by go run ./tools/generate; DO NOT EDIT.\n\n")
	builder.WriteString("package atlasprotocol\n\n")
	builder.WriteString("// ProtocolRevision identifies the protocol CUE source used to generate this package.\n")
	builder.WriteString("const ProtocolRevision = ")
	builder.WriteString(fmt.Sprintf("%q", revision))
	builder.WriteString("\n")
	return formatGeneratedGoSource(builder.String())
}
