package artifacts

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/url"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

type typeScriptSchema map[string]any

func typeScriptSource(revision string, schemas map[string][]byte) ([]byte, error) {
	revision, err := validateProtocolRevision(revision)
	if err != nil {
		return nil, err
	}
	gen := &typeScriptGenerator{
		defs: make(map[string]typeScriptSchema),
	}
	names := make([]string, 0, len(schemas))
	for name := range schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		var root typeScriptSchema
		if err := json.Unmarshal(schemas[name], &root); err != nil {
			return nil, fmt.Errorf("parse %s schema for TypeScript: %w", name, err)
		}
		if err := gen.collectDefs(root); err != nil {
			return nil, err
		}
		if err := gen.addDef(name, stripSchemaMetadata(root)); err != nil {
			return nil, err
		}
	}

	var builder strings.Builder
	builder.WriteString("// Code generated by go run ./tools/generate; DO NOT EDIT.\n\n")
	builder.WriteString("export const ATLAS_PROTOCOL_REVISION = ")
	builder.WriteString(jsonString(revision))
	builder.WriteString(" as const;\n")
	builder.WriteString("export type AtlasProtocolRevision = typeof ATLAS_PROTOCOL_REVISION;\n\n")
	builder.WriteString("type RequireAtLeastOne<T, Keys extends keyof T = keyof T> = Keys extends keyof T ? Required<Pick<T, Keys>> & Partial<Omit<T, Keys>> : never;\n\n")

	defNames := make([]string, 0, len(gen.defs))
	for name := range gen.defs {
		defNames = append(defNames, name)
	}
	sort.Strings(defNames)
	for _, name := range defNames {
		builder.WriteString("export type ")
		builder.WriteString(name)
		builder.WriteString(" = ")
		builder.WriteString(gen.typeFor(gen.defs[name], name, 0))
		builder.WriteString(";\n\n")
	}
	validatorSource, err := taskCreateRequestValidatorSource(gen.defs["TaskCreateRequest"])
	if err != nil {
		return nil, err
	}
	builder.WriteString(validatorSource)
	return formatTypeScript([]byte(builder.String())), nil
}

type typeScriptGenerator struct {
	defs map[string]typeScriptSchema
}

func (g *typeScriptGenerator) collectDefs(root typeScriptSchema) error {
	rawDefs, ok := root["$defs"].(map[string]any)
	if !ok {
		return nil
	}
	keys := make([]string, 0, len(rawDefs))
	for key := range rawDefs {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		schema, ok := rawDefs[key].(map[string]any)
		if !ok {
			continue
		}
		name := typeName(key)
		if isSelfRefType(name, schema) {
			continue
		}
		if err := g.addDef(name, schema); err != nil {
			return err
		}
	}
	return nil
}

func (g *typeScriptGenerator) addDef(name string, schema typeScriptSchema) error {
	if existing, exists := g.defs[name]; exists {
		if reflect.DeepEqual(existing, schema) {
			return nil
		}
		if isSelfRefType(name, existing) {
			g.defs[name] = schema
			return nil
		}
		return fmt.Errorf("typescript type name collision for %q: existing=%s new=%s", name, summarizeTypeScriptSchema(existing), summarizeTypeScriptSchema(schema))
	}
	g.defs[name] = schema
	return nil
}

func summarizeTypeScriptSchema(schema typeScriptSchema) string {
	keys := make([]string, 0, len(schema))
	for key := range schema {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	parts := make([]string, 0, 3)
	if typ, ok := schema["type"].(string); ok {
		parts = append(parts, "type="+typ)
	}
	if ref, ok := schema["$ref"].(string); ok {
		parts = append(parts, "ref="+ref)
	}
	parts = append(parts, "keys="+strings.Join(keys, ","))
	return strings.Join(parts, " ")
}

func stripSchemaMetadata(root typeScriptSchema) typeScriptSchema {
	out := make(typeScriptSchema, len(root))
	for key, value := range root {
		switch key {
		case "$schema", "$comment", "$defs", "x-atlas-protocol-revision":
			continue
		default:
			out[key] = value
		}
	}
	return out
}

func isSelfRefType(name string, schema typeScriptSchema) bool {
	ref, ok := schema["$ref"].(string)
	return ok && typeNameFromRef(ref) == name
}

func (g *typeScriptGenerator) typeFor(schema typeScriptSchema, current string, indent int) string {
	if ref, ok := schema["$ref"].(string); ok {
		return typeNameFromRef(ref)
	}
	if value, ok := schema["const"]; ok {
		return literalType(value)
	}
	if enumValues, ok := schema["enum"].([]any); ok {
		parts := make([]string, 0, len(enumValues))
		for _, value := range enumValues {
			parts = append(parts, literalType(value))
		}
		return strings.Join(parts, " | ")
	}
	if anyOf, ok := schema["anyOf"].([]any); ok {
		return g.unionType(anyOf, current, indent)
	}
	if oneOf, ok := schema["oneOf"].([]any); ok {
		return g.unionType(oneOf, current, indent)
	}
	if allOf, ok := schema["allOf"].([]any); ok {
		return g.intersectionType(allOf, current, indent)
	}

	switch schemaTypeValue(schema) {
	case "null":
		return "null"
	case "boolean":
		return "boolean"
	case "string":
		return "string"
	case "integer", "number":
		return "number"
	case "array":
		return g.arrayType(schema, current, indent)
	case "object":
		return g.objectType(schema, current, indent)
	default:
		if _, ok := schema["properties"].(map[string]any); ok {
			return g.objectType(schema, current, indent)
		}
		if _, ok := schema["additionalProperties"].(map[string]any); ok {
			return g.objectType(schema, current, indent)
		}
		return "unknown"
	}
}

func (g *typeScriptGenerator) unionType(items []any, current string, indent int) string {
	parts := make([]string, 0, len(items))
	for _, item := range items {
		if schema, ok := item.(map[string]any); ok {
			parts = append(parts, g.typeFor(schema, current, indent))
		}
	}
	if len(parts) == 0 {
		return "unknown"
	}
	return strings.Join(uniqueStrings(parts), " | ")
}

func (g *typeScriptGenerator) intersectionType(items []any, current string, indent int) string {
	parts := make([]string, 0, len(items))
	for _, item := range items {
		if schema, ok := item.(map[string]any); ok {
			parts = append(parts, g.typeFor(schema, current, indent))
		}
	}
	if len(parts) == 0 {
		return "unknown"
	}
	return strings.Join(uniqueStrings(parts), " & ")
}

func (g *typeScriptGenerator) arrayType(schema typeScriptSchema, current string, indent int) string {
	if prefixItems, ok := schema["prefixItems"].([]any); ok {
		parts := make([]string, 0, len(prefixItems))
		for _, item := range prefixItems {
			if itemSchema, ok := item.(map[string]any); ok {
				parts = append(parts, g.typeFor(itemSchema, current, indent))
			}
		}
		return "[" + strings.Join(parts, ", ") + "]"
	}
	if itemSchema, ok := schema["items"].(map[string]any); ok {
		itemType := g.typeFor(itemSchema, current, indent)
		if strings.Contains(itemType, " | ") || strings.Contains(itemType, " & ") {
			itemType = "(" + itemType + ")"
		}
		return itemType + "[]"
	}
	return "unknown[]"
}

func (g *typeScriptGenerator) objectType(schema typeScriptSchema, current string, indent int) string {
	props, _ := schema["properties"].(map[string]any)
	required := requiredProperties(schema)
	additional := schema["additionalProperties"]
	patterns, _ := schema["patternProperties"].(map[string]any)

	if len(props) == 0 && len(patterns) == 0 {
		if additionalSchema, ok := additional.(map[string]any); ok {
			return "{ [key: string]: " + g.typeFor(additionalSchema, current, indent) + " }"
		}
		if allowed, ok := additional.(bool); ok && !allowed {
			return "Record<string, never>"
		}
		return "Record<string, unknown>"
	}

	innerIndent := strings.Repeat("\t", indent+1)
	outerIndent := strings.Repeat("\t", indent)
	var builder strings.Builder
	builder.WriteString("{\n")

	keys := make([]string, 0, len(props))
	for key := range props {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		propSchema, ok := props[key].(map[string]any)
		if !ok {
			continue
		}
		builder.WriteString(innerIndent)
		builder.WriteString(jsonString(key))
		if !required[key] {
			builder.WriteString("?")
		}
		builder.WriteString(": ")
		builder.WriteString(g.typeFor(propSchema, current, indent+1))
		builder.WriteString(";\n")
	}

	patternKeys := make([]string, 0, len(patterns))
	for key := range patterns {
		patternKeys = append(patternKeys, key)
	}
	sort.Strings(patternKeys)
	for _, key := range patternKeys {
		patternSchema, ok := patterns[key].(map[string]any)
		if !ok {
			continue
		}
		builder.WriteString(innerIndent)
		if strings.HasPrefix(key, "^custom_") {
			builder.WriteString("[key: `custom_${string}`]: ")
		} else {
			builder.WriteString("[key: string]: ")
		}
		builder.WriteString(g.typeFor(patternSchema, current, indent+1))
		builder.WriteString(";\n")
	}

	if additionalSchema, ok := additional.(map[string]any); ok {
		builder.WriteString(innerIndent)
		builder.WriteString("[key: string]: ")
		if len(props) > 0 {
			builder.WriteString("unknown")
		} else {
			builder.WriteString(g.typeFor(additionalSchema, current, indent+1))
		}
		builder.WriteString(";\n")
	}
	builder.WriteString(outerIndent)
	builder.WriteString("}")
	shape := builder.String()
	if minPropertiesOne(schema) && len(required) == 0 && len(keys) > 0 {
		return "RequireAtLeastOne<" + shape + ", " + quotedUnion(keys) + ">"
	}
	return shape
}

func minPropertiesOne(schema typeScriptSchema) bool {
	value, ok := schema["minProperties"].(float64)
	return ok && value == 1
}

func quotedUnion(values []string) string {
	parts := make([]string, 0, len(values))
	for _, value := range values {
		parts = append(parts, jsonString(value))
	}
	return strings.Join(parts, " | ")
}

func taskCreateRequestValidatorSource(schema typeScriptSchema) (string, error) {
	props, ok := schema["properties"].(map[string]any)
	if !ok {
		return "", fmt.Errorf("TaskCreateRequest schema has no properties")
	}
	required := requiredProperties(schema)
	keys := make([]string, 0, len(props))
	for key := range props {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var checks []string
	for _, key := range keys {
		propSchema, ok := props[key].(map[string]any)
		if !ok {
			return "", fmt.Errorf("TaskCreateRequest property %s is not a schema", key)
		}
		check, err := runtimeValidatorExpression("value."+key, propSchema)
		if err != nil {
			return "", fmt.Errorf("TaskCreateRequest property %s: %w", key, err)
		}
		if required[key] {
			checks = append(checks, "atlasProtocolHasOwn(value, "+jsonString(key)+") && "+check)
		} else {
			checks = append(checks, "(value."+key+" === undefined || "+check+")")
		}
	}

	var builder strings.Builder
	builder.WriteString("export function isTaskCreateRequest(value: unknown): value is TaskCreateRequest {\n")
	builder.WriteString("  if (!atlasProtocolIsRecord(value)) {\n")
	builder.WriteString("    return false;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  const allowedKeys = new Set(")
	builder.WriteString(jsonStringSlice(keys))
	builder.WriteString(");\n")
	builder.WriteString("  return Object.keys(value).every((key) => allowedKeys.has(key))")
	for _, check := range checks {
		builder.WriteString(" &&\n    ")
		builder.WriteString(check)
	}
	builder.WriteString(";\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolHasOwn(value: Record<string, unknown>, key: string): boolean {\n")
	builder.WriteString("  return Object.prototype.hasOwnProperty.call(value, key);\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolIsRecord(value: unknown): value is Record<string, unknown> {\n")
	builder.WriteString("  return typeof value === \"object\" && value !== null && !Array.isArray(value);\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolIsNonEmptyString(value: unknown): value is string {\n")
	builder.WriteString("  return typeof value === \"string\" && value.trim() !== \"\";\n")
	builder.WriteString("}\n\n")
	return builder.String(), nil
}

func runtimeValidatorExpression(valueExpr string, schema typeScriptSchema) (string, error) {
	if ref, ok := schema["$ref"].(string); ok {
		switch typeNameFromRef(ref) {
		case "NonEmptyString":
			return "atlasProtocolIsNonEmptyString(" + valueExpr + ")", nil
		case "TaskComponents", "JSONValue":
			return "atlasProtocolIsRecord(" + valueExpr + ")", nil
		default:
			return "true", nil
		}
	}
	if oneOf, ok := schema["oneOf"].([]any); ok {
		return runtimeUnionValidatorExpression(valueExpr, oneOf)
	}
	if anyOf, ok := schema["anyOf"].([]any); ok {
		return runtimeUnionValidatorExpression(valueExpr, anyOf)
	}
	switch schemaTypeValue(schema) {
	case "null":
		return valueExpr + " === null", nil
	case "string":
		if _, ok := schema["pattern"].(string); ok {
			return "atlasProtocolIsNonEmptyString(" + valueExpr + ")", nil
		}
		return "typeof " + valueExpr + " === \"string\"", nil
	case "object":
		return "atlasProtocolIsRecord(" + valueExpr + ")", nil
	default:
		if _, ok := schema["additionalProperties"]; ok {
			return "atlasProtocolIsRecord(" + valueExpr + ")", nil
		}
		return "true", nil
	}
}

func runtimeUnionValidatorExpression(valueExpr string, items []any) (string, error) {
	parts := make([]string, 0, len(items))
	for _, item := range items {
		schema, ok := item.(map[string]any)
		if !ok {
			continue
		}
		expression, err := runtimeValidatorExpression(valueExpr, schema)
		if err != nil {
			return "", err
		}
		parts = append(parts, expression)
	}
	if len(parts) == 0 {
		return "true", nil
	}
	return "(" + strings.Join(uniqueStrings(parts), " || ") + ")", nil
}

func jsonStringSlice(values []string) string {
	encoded, err := json.Marshal(values)
	if err != nil {
		panic(err)
	}
	return string(encoded)
}

func requiredProperties(schema typeScriptSchema) map[string]bool {
	required := map[string]bool{}
	values, ok := schema["required"].([]any)
	if !ok {
		return required
	}
	for _, value := range values {
		if key, ok := value.(string); ok {
			required[key] = true
		}
	}
	return required
}

func schemaTypeValue(schema typeScriptSchema) string {
	if value, ok := schema["type"].(string); ok {
		return value
	}
	return ""
}

func typeNameFromRef(ref string) string {
	const prefix = "#/$defs/"
	if strings.HasPrefix(ref, prefix) {
		raw, err := url.PathUnescape(strings.TrimPrefix(ref, prefix))
		if err == nil {
			return typeName(raw)
		}
		return typeName(strings.TrimPrefix(ref, prefix))
	}
	return typeName(ref)
}

var nonIdentifierChars = regexp.MustCompile(`[^A-Za-z0-9]+`)

func typeName(raw string) string {
	raw = strings.TrimPrefix(raw, "#")
	raw = nonIdentifierChars.ReplaceAllString(raw, " ")
	parts := strings.Fields(raw)
	if len(parts) == 0 {
		return "Unknown"
	}
	for i, part := range parts {
		parts[i] = upperFirst(part)
	}
	name := strings.Join(parts, "")
	if len(name) > 0 && unicode.IsDigit(rune(name[0])) {
		name = "Atlas" + name
	}
	return name
}

func upperFirst(value string) string {
	if value == "" {
		return value
	}
	runes := []rune(value)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func literalType(value any) string {
	switch typed := value.(type) {
	case nil:
		return "null"
	case bool:
		if typed {
			return "true"
		}
		return "false"
	case string:
		return jsonString(typed)
	case float64:
		return fmt.Sprintf("%v", typed)
	case map[string]any:
		keys := make([]string, 0, len(typed))
		for key := range typed {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		parts := make([]string, 0, len(keys))
		for _, key := range keys {
			parts = append(parts, jsonString(key)+": "+literalType(typed[key]))
		}
		return "{ " + strings.Join(parts, "; ") + " }"
	case []any:
		parts := make([]string, 0, len(typed))
		for _, item := range typed {
			parts = append(parts, literalType(item))
		}
		return "[" + strings.Join(parts, ", ") + "]"
	default:
		return jsonString(fmt.Sprint(typed))
	}
}

func jsonString(value string) string {
	data, _ := json.Marshal(value)
	return string(data)
}

func uniqueStrings(values []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(values))
	for _, value := range values {
		if seen[value] {
			continue
		}
		seen[value] = true
		out = append(out, value)
	}
	return out
}

func formatTypeScript(source []byte) []byte {
	formatted := bytes.ReplaceAll(source, []byte("\t"), []byte("  "))
	return append(bytes.TrimRight(formatted, "\n"), '\n')
}
