package artifacts

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/url"
	"reflect"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

type typeScriptSchema map[string]any

func typeScriptSource(revision string, schemas map[string][]byte) ([]byte, error) {
	revision, err := validateProtocolRevision(revision)
	if err != nil {
		return nil, err
	}
	gen := &typeScriptGenerator{
		defs: make(map[string]typeScriptSchema),
	}
	names := make([]string, 0, len(schemas))
	for name := range schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		var root typeScriptSchema
		if err := json.Unmarshal(schemas[name], &root); err != nil {
			return nil, fmt.Errorf("parse %s schema for TypeScript: %w", name, err)
		}
		if err := gen.collectDefs(root); err != nil {
			return nil, err
		}
		if err := gen.addDef(name, stripSchemaMetadata(root)); err != nil {
			return nil, err
		}
	}

	var builder strings.Builder
	builder.WriteString("// Code generated by go run ./tools/generate; DO NOT EDIT.\n\n")
	builder.WriteString("export const ATLAS_PROTOCOL_REVISION = ")
	builder.WriteString(jsonString(revision))
	builder.WriteString(" as const;\n")
	builder.WriteString("export type AtlasProtocolRevision = typeof ATLAS_PROTOCOL_REVISION;\n\n")
	builder.WriteString("type RequireAtLeastOne<T, Keys extends keyof T = keyof T> = Keys extends keyof T ? Required<Pick<T, Keys>> & Partial<Omit<T, Keys>> : never;\n\n")

	defNames := make([]string, 0, len(gen.defs))
	for name := range gen.defs {
		defNames = append(defNames, name)
	}
	sort.Strings(defNames)
	for _, name := range defNames {
		builder.WriteString("export type ")
		builder.WriteString(name)
		builder.WriteString(" = ")
		builder.WriteString(gen.typeFor(gen.defs[name], name, 0))
		builder.WriteString(";\n\n")
	}
	validatorSource, err := requestValidatorSource(gen)
	if err != nil {
		return nil, err
	}
	builder.WriteString(validatorSource)
	return formatTypeScript([]byte(builder.String())), nil
}

type typeScriptGenerator struct {
	defs map[string]typeScriptSchema
}

func (g *typeScriptGenerator) collectDefs(root typeScriptSchema) error {
	rawDefs, ok := root["$defs"].(map[string]any)
	if !ok {
		return nil
	}
	keys := make([]string, 0, len(rawDefs))
	for key := range rawDefs {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		schema, ok := rawDefs[key].(map[string]any)
		if !ok {
			continue
		}
		name := typeName(key)
		if isSelfRefType(name, schema) {
			continue
		}
		if err := g.addDef(name, schema); err != nil {
			return err
		}
	}
	return nil
}

func (g *typeScriptGenerator) addDef(name string, schema typeScriptSchema) error {
	if existing, exists := g.defs[name]; exists {
		if reflect.DeepEqual(existing, schema) {
			return nil
		}
		if isSelfRefType(name, existing) {
			g.defs[name] = schema
			return nil
		}
		return fmt.Errorf("typescript type name collision for %q: existing=%s new=%s", name, summarizeTypeScriptSchema(existing), summarizeTypeScriptSchema(schema))
	}
	g.defs[name] = schema
	return nil
}

func summarizeTypeScriptSchema(schema typeScriptSchema) string {
	keys := make([]string, 0, len(schema))
	for key := range schema {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	parts := make([]string, 0, 3)
	if typ, ok := schema["type"].(string); ok {
		parts = append(parts, "type="+typ)
	}
	if ref, ok := schema["$ref"].(string); ok {
		parts = append(parts, "ref="+ref)
	}
	parts = append(parts, "keys="+strings.Join(keys, ","))
	return strings.Join(parts, " ")
}

func stripSchemaMetadata(root typeScriptSchema) typeScriptSchema {
	out := make(typeScriptSchema, len(root))
	for key, value := range root {
		switch key {
		case "$schema", "$comment", "$defs", "x-atlas-protocol-revision":
			continue
		default:
			out[key] = value
		}
	}
	return out
}

func isSelfRefType(name string, schema typeScriptSchema) bool {
	ref, ok := schema["$ref"].(string)
	return ok && typeNameFromRef(ref) == name
}

func (g *typeScriptGenerator) typeFor(schema typeScriptSchema, current string, indent int) string {
	if ref, ok := schema["$ref"].(string); ok {
		return typeNameFromRef(ref)
	}
	if value, ok := schema["const"]; ok {
		return literalType(value)
	}
	if enumValues, ok := schema["enum"].([]any); ok {
		parts := make([]string, 0, len(enumValues))
		for _, value := range enumValues {
			parts = append(parts, literalType(value))
		}
		return strings.Join(parts, " | ")
	}
	if anyOf, ok := schema["anyOf"].([]any); ok {
		return g.unionType(anyOf, current, indent)
	}
	if oneOf, ok := schema["oneOf"].([]any); ok {
		return g.unionType(oneOf, current, indent)
	}
	if allOf, ok := schema["allOf"].([]any); ok {
		return g.intersectionType(allOf, current, indent)
	}

	switch schemaTypeValue(schema) {
	case "null":
		return "null"
	case "boolean":
		return "boolean"
	case "string":
		return "string"
	case "integer", "number":
		return "number"
	case "array":
		return g.arrayType(schema, current, indent)
	case "object":
		return g.objectType(schema, current, indent)
	default:
		if _, ok := schema["properties"].(map[string]any); ok {
			return g.objectType(schema, current, indent)
		}
		if _, ok := schema["additionalProperties"].(map[string]any); ok {
			return g.objectType(schema, current, indent)
		}
		return "unknown"
	}
}

func (g *typeScriptGenerator) unionType(items []any, current string, indent int) string {
	parts := make([]string, 0, len(items))
	for _, item := range items {
		if schema, ok := item.(map[string]any); ok {
			parts = append(parts, g.typeFor(schema, current, indent))
		}
	}
	if len(parts) == 0 {
		return "unknown"
	}
	return strings.Join(uniqueStrings(parts), " | ")
}

func (g *typeScriptGenerator) intersectionType(items []any, current string, indent int) string {
	parts := make([]string, 0, len(items))
	for _, item := range items {
		if schema, ok := item.(map[string]any); ok {
			parts = append(parts, g.typeFor(schema, current, indent))
		}
	}
	if len(parts) == 0 {
		return "unknown"
	}
	return strings.Join(uniqueStrings(parts), " & ")
}

func (g *typeScriptGenerator) arrayType(schema typeScriptSchema, current string, indent int) string {
	if prefixItems, ok := schema["prefixItems"].([]any); ok {
		parts := make([]string, 0, len(prefixItems))
		for _, item := range prefixItems {
			if itemSchema, ok := item.(map[string]any); ok {
				parts = append(parts, g.typeFor(itemSchema, current, indent))
			}
		}
		return "[" + strings.Join(parts, ", ") + "]"
	}
	if itemSchema, ok := schema["items"].(map[string]any); ok {
		itemType := g.typeFor(itemSchema, current, indent)
		if strings.Contains(itemType, " | ") || strings.Contains(itemType, " & ") {
			itemType = "(" + itemType + ")"
		}
		return itemType + "[]"
	}
	return "unknown[]"
}

func (g *typeScriptGenerator) objectType(schema typeScriptSchema, current string, indent int) string {
	props, _ := schema["properties"].(map[string]any)
	required := requiredProperties(schema)
	additional := schema["additionalProperties"]
	patterns, _ := schema["patternProperties"].(map[string]any)

	if len(props) == 0 && len(patterns) == 0 {
		if additionalSchema, ok := additional.(map[string]any); ok {
			return "{ [key: string]: " + g.typeFor(additionalSchema, current, indent) + " }"
		}
		if allowed, ok := additional.(bool); ok && !allowed {
			return "Record<string, never>"
		}
		return "Record<string, unknown>"
	}

	innerIndent := strings.Repeat("\t", indent+1)
	outerIndent := strings.Repeat("\t", indent)
	var builder strings.Builder
	builder.WriteString("{\n")

	keys := make([]string, 0, len(props))
	for key := range props {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		propSchema, ok := props[key].(map[string]any)
		if !ok {
			continue
		}
		builder.WriteString(innerIndent)
		builder.WriteString(jsonString(key))
		if !required[key] {
			builder.WriteString("?")
		}
		builder.WriteString(": ")
		builder.WriteString(g.typeFor(propSchema, current, indent+1))
		builder.WriteString(";\n")
	}

	patternKeys := make([]string, 0, len(patterns))
	for key := range patterns {
		patternKeys = append(patternKeys, key)
	}
	sort.Strings(patternKeys)
	for _, key := range patternKeys {
		patternSchema, ok := patterns[key].(map[string]any)
		if !ok {
			continue
		}
		builder.WriteString(innerIndent)
		if strings.HasPrefix(key, "^custom_") {
			builder.WriteString("[key: `custom_${string}`]: ")
		} else {
			builder.WriteString("[key: string]: ")
		}
		builder.WriteString(g.typeFor(patternSchema, current, indent+1))
		builder.WriteString(";\n")
	}

	if additionalSchema, ok := additional.(map[string]any); ok {
		builder.WriteString(innerIndent)
		builder.WriteString("[key: string]: ")
		builder.WriteString(g.additionalPropertyIndexType(additionalSchema, props, required, current, indent+1))
		builder.WriteString(";\n")
	}
	builder.WriteString(outerIndent)
	builder.WriteString("}")
	shape := builder.String()
	if minPropertiesOne(schema) && len(required) == 0 && len(keys) > 0 {
		return "RequireAtLeastOne<" + shape + ", " + quotedUnion(keys) + ">"
	}
	return shape
}

func (g *typeScriptGenerator) additionalPropertyIndexType(additionalSchema typeScriptSchema, props map[string]any, required map[string]bool, current string, indent int) string {
	parts := []string{g.typeFor(additionalSchema, current, indent)}
	hasOptional := false
	keys := make([]string, 0, len(props))
	for key := range props {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		propSchema, ok := props[key].(map[string]any)
		if !ok {
			continue
		}
		parts = append(parts, g.typeFor(propSchema, current, indent))
		if !required[key] {
			hasOptional = true
		}
	}
	if hasOptional {
		parts = append(parts, "undefined")
	}
	return strings.Join(uniqueStrings(parts), " | ")
}

func minPropertiesOne(schema typeScriptSchema) bool {
	value, ok := schema["minProperties"].(float64)
	return ok && value == 1
}

func quotedUnion(values []string) string {
	parts := make([]string, 0, len(values))
	for _, value := range values {
		parts = append(parts, jsonString(value))
	}
	return strings.Join(parts, " | ")
}

var requestValidatorTypeNames = []string{
	"EntityCreateRequest",
	"EntityUpdateRequest",
	"ObjectCreateRequest",
	"ObjectUpdateRequest",
	"TaskCreateRequest",
	"TaskUpdateRequest",
}

func requestValidatorSource(g *typeScriptGenerator) (string, error) {
	var builder strings.Builder
	generated := false
	for _, name := range requestValidatorTypeNames {
		schema, ok := g.defs[name]
		if !ok {
			continue
		}
		generated = true
		check, err := g.runtimeValidatorExpression("value", schema)
		if err != nil {
			return "", fmt.Errorf("%s: %w", name, err)
		}
		builder.WriteString("export function ")
		builder.WriteString(validatorFunctionName(name))
		builder.WriteString("(value: unknown): value is ")
		builder.WriteString(name)
		builder.WriteString(" {\n")
		builder.WriteString("  return ")
		builder.WriteString(check)
		builder.WriteString(";\n")
		builder.WriteString("}\n\n")
	}
	if !generated {
		return "", nil
	}
	builder.WriteString(runtimeValidatorHelpersSource())
	return builder.String(), nil
}

func validatorFunctionName(typeName string) string {
	return "is" + typeName
}

func (g *typeScriptGenerator) runtimeValidatorExpression(valueExpr string, schema typeScriptSchema) (string, error) {
	if ref, ok := schema["$ref"].(string); ok {
		refExpression, err := g.runtimeRefValidatorExpression(valueExpr, ref)
		if err != nil {
			return "", err
		}
		siblingSchema := cloneSchemaWithoutKey(schema, "$ref")
		if len(siblingSchema) == 0 {
			return refExpression, nil
		}
		siblingExpression, err := g.runtimeValidatorExpression(valueExpr, siblingSchema)
		if err != nil {
			return "", err
		}
		return "(" + refExpression + " && " + siblingExpression + ")", nil
	}
	if oneOf, ok := schema["oneOf"].([]any); ok {
		return g.runtimeUnionValidatorExpression(valueExpr, oneOf)
	}
	if anyOf, ok := schema["anyOf"].([]any); ok {
		return g.runtimeUnionValidatorExpression(valueExpr, anyOf)
	}
	if allOf, ok := schema["allOf"].([]any); ok {
		return g.runtimeAllOfValidatorExpression(valueExpr, allOf)
	}
	if value, ok := schema["const"]; ok {
		return valueExpr + " === " + literalValue(value), nil
	}
	if enumValues, ok := schema["enum"].([]any); ok {
		parts := make([]string, 0, len(enumValues))
		for _, value := range enumValues {
			parts = append(parts, valueExpr+" === "+literalValue(value))
		}
		if len(parts) == 0 {
			return "", fmt.Errorf("runtime enum has no values")
		}
		return "(" + strings.Join(parts, " || ") + ")", nil
	}

	switch schemaTypeValue(schema) {
	case "null":
		return valueExpr + " === null", nil
	case "string":
		return runtimeStringValidatorExpression(valueExpr, schema), nil
	case "integer":
		return runtimeNumberValidatorExpression(valueExpr, schema, true), nil
	case "number":
		return runtimeNumberValidatorExpression(valueExpr, schema, false), nil
	case "boolean":
		return "typeof " + valueExpr + " === \"boolean\"", nil
	case "array":
		return g.runtimeArrayValidatorExpression(valueExpr, schema)
	case "object":
		return g.runtimeObjectValidatorExpression(valueExpr, schema)
	default:
		if _, ok := schema["properties"].(map[string]any); ok {
			return g.runtimeObjectValidatorExpression(valueExpr, schema)
		}
		if _, ok := schema["additionalProperties"].(map[string]any); ok {
			return g.runtimeObjectValidatorExpression(valueExpr, schema)
		}
		if _, ok := schema["additionalProperties"].(bool); ok {
			return g.runtimeObjectValidatorExpression(valueExpr, schema)
		}
		return "", fmt.Errorf("unsupported runtime validator schema: %s", summarizeTypeScriptSchema(schema))
	}
}

func (g *typeScriptGenerator) runtimeRefValidatorExpression(valueExpr string, ref string) (string, error) {
	name := typeNameFromRef(ref)
	switch name {
	case "JSONValue":
		return "atlasProtocolIsJSONValue(" + valueExpr + ")", nil
	case "NonEmptyString":
		return "atlasProtocolIsNonEmptyString(" + valueExpr + ")", nil
	case "RFC3339Timestamp":
		return "atlasProtocolIsRFC3339String(" + valueExpr + ")", nil
	}
	schema, ok := g.defs[name]
	if !ok {
		return "", fmt.Errorf("unsupported runtime validator ref %q", ref)
	}
	return g.runtimeValidatorExpression(valueExpr, schema)
}

func runtimeStringValidatorExpression(valueExpr string, schema typeScriptSchema) string {
	if format, ok := schema["format"].(string); ok && format == "date-time" {
		return "atlasProtocolIsRFC3339String(" + valueExpr + ")"
	}
	if _, ok := schema["pattern"].(string); ok {
		return "atlasProtocolIsNonEmptyString(" + valueExpr + ")"
	}
	if minLength, ok := schema["minLength"].(float64); ok && minLength > 0 {
		return "atlasProtocolIsNonEmptyString(" + valueExpr + ")"
	}
	return "typeof " + valueExpr + " === \"string\""
}

func runtimeNumberValidatorExpression(valueExpr string, schema typeScriptSchema, integer bool) string {
	checks := []string{"typeof " + valueExpr + " === \"number\"", "Number.isFinite(" + valueExpr + ")"}
	if integer {
		checks = append(checks, "Number.isInteger("+valueExpr+")")
	}
	if minimum, ok := schema["minimum"].(float64); ok {
		checks = append(checks, valueExpr+" >= "+jsonNumber(minimum))
	}
	if maximum, ok := schema["maximum"].(float64); ok {
		checks = append(checks, valueExpr+" <= "+jsonNumber(maximum))
	}
	if exclusiveMinimum, ok := schema["exclusiveMinimum"].(float64); ok {
		checks = append(checks, valueExpr+" > "+jsonNumber(exclusiveMinimum))
	}
	if exclusiveMaximum, ok := schema["exclusiveMaximum"].(float64); ok {
		checks = append(checks, valueExpr+" < "+jsonNumber(exclusiveMaximum))
	}
	return strings.Join(checks, " && ")
}

func (g *typeScriptGenerator) runtimeArrayValidatorExpression(valueExpr string, schema typeScriptSchema) (string, error) {
	if itemSchema, ok := schema["items"].(map[string]any); ok {
		itemCheck, err := g.runtimeValidatorExpression("item", itemSchema)
		if err != nil {
			return "", err
		}
		return "Array.isArray(" + valueExpr + ") && " + valueExpr + ".every((item) => " + itemCheck + ")", nil
	}
	return "Array.isArray(" + valueExpr + ")", nil
}

func (g *typeScriptGenerator) runtimeObjectValidatorExpression(valueExpr string, schema typeScriptSchema) (string, error) {
	props, _ := schema["properties"].(map[string]any)
	patterns, _ := schema["patternProperties"].(map[string]any)
	required := requiredProperties(schema)

	keys := make([]string, 0, len(props))
	for key := range props {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	checks := []string{"atlasProtocolIsRecord(" + valueExpr + ")"}
	if minPropertiesOne(schema) {
		checks = append(checks, "Object.keys("+valueExpr+").length >= 1")
	}
	for _, key := range keys {
		propSchema, ok := props[key].(map[string]any)
		if !ok {
			return "", fmt.Errorf("property %s is not a schema", key)
		}
		propExpr := valueExpr + "[" + jsonString(key) + "]"
		check, err := g.runtimeValidatorExpression(propExpr, propSchema)
		if err != nil {
			return "", fmt.Errorf("property %s: %w", key, err)
		}
		if required[key] {
			checks = append(checks, "(atlasProtocolHasOwn("+valueExpr+", "+jsonString(key)+") && "+check+")")
		} else {
			checks = append(checks, "(!atlasProtocolHasOwn("+valueExpr+", "+jsonString(key)+") || "+check+")")
		}
	}

	entriesCheck, err := g.runtimeObjectEntriesValidatorExpression(valueExpr, keys, patterns, schema["additionalProperties"])
	if err != nil {
		return "", err
	}
	if entriesCheck != "" {
		checks = append(checks, entriesCheck)
	}
	return "(" + strings.Join(checks, " && ") + ")", nil
}

func (g *typeScriptGenerator) runtimeObjectEntriesValidatorExpression(valueExpr string, propKeys []string, patterns map[string]any, additional any) (string, error) {
	if len(patterns) == 0 {
		switch typed := additional.(type) {
		case nil:
			return "", nil
		case bool:
			if typed {
				return "", nil
			}
			return "Object.keys(" + valueExpr + ").every((key) => atlasProtocolKnownKeys(" + jsonStringSlice(propKeys) + ", key))", nil
		case map[string]any:
			check, err := g.runtimeValidatorExpression("item", typed)
			if err != nil {
				return "", err
			}
			return "Object.entries(" + valueExpr + ").every(([key, item]) => atlasProtocolKnownKeys(" + jsonStringSlice(propKeys) + ", key) || " + check + ")", nil
		default:
			return "", fmt.Errorf("unsupported additionalProperties %T", additional)
		}
	}

	patternKeys := make([]string, 0, len(patterns))
	for key := range patterns {
		patternKeys = append(patternKeys, key)
	}
	sort.Strings(patternKeys)

	patternChecks := make([]string, 0, len(patternKeys))
	for _, pattern := range patternKeys {
		patternSchema, ok := patterns[pattern].(map[string]any)
		if !ok {
			return "", fmt.Errorf("pattern %s is not a schema", pattern)
		}
		itemCheck, err := g.runtimeValidatorExpression("item", patternSchema)
		if err != nil {
			return "", fmt.Errorf("pattern %s: %w", pattern, err)
		}
		patternChecks = append(patternChecks, "(atlasProtocolKeyMatches(key, "+jsonString(pattern)+") && "+itemCheck+")")
	}

	fallback := "true"
	switch typed := additional.(type) {
	case nil:
		fallback = "true"
	case bool:
		if !typed {
			fallback = "false"
		}
	case map[string]any:
		check, err := g.runtimeValidatorExpression("item", typed)
		if err != nil {
			return "", err
		}
		fallback = check
	default:
		return "", fmt.Errorf("unsupported additionalProperties %T", additional)
	}

	parts := []string{"atlasProtocolKnownKeys(" + jsonStringSlice(propKeys) + ", key)"}
	parts = append(parts, patternChecks...)
	parts = append(parts, fallback)
	return "Object.entries(" + valueExpr + ").every(([key, item]) => " + strings.Join(parts, " || ") + ")", nil
}

func (g *typeScriptGenerator) runtimeUnionValidatorExpression(valueExpr string, items []any) (string, error) {
	parts := make([]string, 0, len(items))
	for _, item := range items {
		schema, ok := item.(map[string]any)
		if !ok {
			return "", fmt.Errorf("unsupported runtime union item %T", item)
		}
		expression, err := g.runtimeValidatorExpression(valueExpr, schema)
		if err != nil {
			return "", err
		}
		parts = append(parts, expression)
	}
	if len(parts) == 0 {
		return "", fmt.Errorf("runtime union has no schema branches")
	}
	return "(" + strings.Join(uniqueStrings(parts), " || ") + ")", nil
}

func (g *typeScriptGenerator) runtimeAllOfValidatorExpression(valueExpr string, items []any) (string, error) {
	parts := make([]string, 0, len(items))
	for _, item := range items {
		schema, ok := item.(map[string]any)
		if !ok {
			return "", fmt.Errorf("unsupported runtime allOf item %T", item)
		}
		expression, err := g.runtimeValidatorExpression(valueExpr, schema)
		if err != nil {
			return "", err
		}
		parts = append(parts, expression)
	}
	if len(parts) == 0 {
		return "", fmt.Errorf("runtime allOf has no schema branches")
	}
	return "(" + strings.Join(uniqueStrings(parts), " && ") + ")", nil
}

func runtimeValidatorHelpersSource() string {
	var builder strings.Builder
	builder.WriteString("function atlasProtocolHasOwn(value: Record<string, unknown>, key: string): boolean {\n")
	builder.WriteString("  return Object.prototype.hasOwnProperty.call(value, key);\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolKnownKeys(keys: readonly string[], key: string): boolean {\n")
	builder.WriteString("  return keys.includes(key);\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolKeyMatches(key: string, pattern: string): boolean {\n")
	builder.WriteString("  return new RegExp(pattern).test(key);\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolIsRecord(value: unknown): value is Record<string, unknown> {\n")
	builder.WriteString("  if (typeof value !== \"object\" || value === null || Array.isArray(value)) {\n")
	builder.WriteString("    return false;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  const prototype = Object.getPrototypeOf(value);\n")
	builder.WriteString("  if (prototype === null) {\n")
	builder.WriteString("    return true;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  let basePrototype = prototype;\n")
	builder.WriteString("  while (Object.getPrototypeOf(basePrototype) !== null) {\n")
	builder.WriteString("    basePrototype = Object.getPrototypeOf(basePrototype);\n")
	builder.WriteString("  }\n")
	builder.WriteString("  return prototype === basePrototype;\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolIsNonEmptyString(value: unknown): value is string {\n")
	builder.WriteString("  return typeof value === \"string\" && value.trim() !== \"\";\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolIsRFC3339String(value: unknown): value is string {\n")
	builder.WriteString("  return typeof value === \"string\" && Number.isFinite(Date.parse(value));\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolIsJSONValue(value: unknown): value is JSONValue {\n")
	builder.WriteString("  return atlasProtocolIsJSONValueInternal(value, new WeakSet<object>());\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolIsJSONValueInternal(value: unknown, seen: WeakSet<object>): value is JSONValue {\n")
	builder.WriteString("  if (value === null) {\n")
	builder.WriteString("    return true;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  switch (typeof value) {\n")
	builder.WriteString("    case \"boolean\":\n")
	builder.WriteString("    case \"string\":\n")
	builder.WriteString("      return true;\n")
	builder.WriteString("    case \"number\":\n")
	builder.WriteString("      return Number.isFinite(value);\n")
	builder.WriteString("    case \"object\":\n")
	builder.WriteString("      if (seen.has(value)) {\n")
	builder.WriteString("        return false;\n")
	builder.WriteString("      }\n")
	builder.WriteString("      seen.add(value);\n")
	builder.WriteString("      if (Array.isArray(value)) {\n")
	builder.WriteString("        const valid = value.every((item) => atlasProtocolIsJSONValueInternal(item, seen));\n")
	builder.WriteString("        seen.delete(value);\n")
	builder.WriteString("        return valid;\n")
	builder.WriteString("      }\n")
	builder.WriteString("      const valid = atlasProtocolIsRecord(value) && Object.values(value).every((item) => atlasProtocolIsJSONValueInternal(item, seen));\n")
	builder.WriteString("      seen.delete(value);\n")
	builder.WriteString("      return valid;\n")
	builder.WriteString("    default:\n")
	builder.WriteString("      return false;\n")
	builder.WriteString("  }\n")
	builder.WriteString("}\n\n")
	return builder.String()
}

func jsonStringSlice(values []string) string {
	encoded, err := json.Marshal(values)
	if err != nil {
		panic(err)
	}
	return string(encoded)
}

func requiredProperties(schema typeScriptSchema) map[string]bool {
	required := map[string]bool{}
	values, ok := schema["required"].([]any)
	if !ok {
		return required
	}
	for _, value := range values {
		if key, ok := value.(string); ok {
			required[key] = true
		}
	}
	return required
}

func schemaTypeValue(schema typeScriptSchema) string {
	if value, ok := schema["type"].(string); ok {
		return value
	}
	return ""
}

func cloneSchemaWithoutKey(schema typeScriptSchema, without string) typeScriptSchema {
	out := make(typeScriptSchema, len(schema))
	for key, value := range schema {
		if key == without {
			continue
		}
		out[key] = value
	}
	return out
}

func typeNameFromRef(ref string) string {
	const prefix = "#/$defs/"
	if strings.HasPrefix(ref, prefix) {
		raw, err := url.PathUnescape(strings.TrimPrefix(ref, prefix))
		if err == nil {
			return typeName(raw)
		}
		return typeName(strings.TrimPrefix(ref, prefix))
	}
	return typeName(ref)
}

var nonIdentifierChars = regexp.MustCompile(`[^A-Za-z0-9]+`)

func typeName(raw string) string {
	raw = strings.TrimPrefix(raw, "#")
	raw = nonIdentifierChars.ReplaceAllString(raw, " ")
	parts := strings.Fields(raw)
	if len(parts) == 0 {
		return "Unknown"
	}
	for i, part := range parts {
		parts[i] = upperFirst(part)
	}
	name := strings.Join(parts, "")
	if len(name) > 0 && unicode.IsDigit(rune(name[0])) {
		name = "Atlas" + name
	}
	return name
}

func upperFirst(value string) string {
	if value == "" {
		return value
	}
	runes := []rune(value)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func literalType(value any) string {
	switch typed := value.(type) {
	case nil:
		return "null"
	case bool:
		if typed {
			return "true"
		}
		return "false"
	case string:
		return jsonString(typed)
	case float64:
		return fmt.Sprintf("%v", typed)
	case map[string]any:
		keys := make([]string, 0, len(typed))
		for key := range typed {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		parts := make([]string, 0, len(keys))
		for _, key := range keys {
			parts = append(parts, jsonString(key)+": "+literalType(typed[key]))
		}
		return "{ " + strings.Join(parts, "; ") + " }"
	case []any:
		parts := make([]string, 0, len(typed))
		for _, item := range typed {
			parts = append(parts, literalType(item))
		}
		return "[" + strings.Join(parts, ", ") + "]"
	default:
		return jsonString(fmt.Sprint(typed))
	}
}

func literalValue(value any) string {
	data, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	return string(data)
}

func jsonNumber(value float64) string {
	return strconv.FormatFloat(value, 'f', -1, 64)
}

func jsonString(value string) string {
	data, _ := json.Marshal(value)
	return string(data)
}

func uniqueStrings(values []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(values))
	for _, value := range values {
		if seen[value] {
			continue
		}
		seen[value] = true
		out = append(out, value)
	}
	return out
}

func formatTypeScript(source []byte) []byte {
	formatted := bytes.ReplaceAll(source, []byte("\t"), []byte("  "))
	return append(bytes.TrimRight(formatted, "\n"), '\n')
}
