package artifacts

import "strings"

func runtimeValidatorHelpersSource() string {
	var builder strings.Builder
	builder.WriteString("function atlasProtocolHasOwn(value: Record<string, unknown>, key: string): boolean {\n")
	builder.WriteString("  return Object.prototype.hasOwnProperty.call(value, key);\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolKnownKeys(keys: readonly string[], key: string): boolean {\n")
	builder.WriteString("  return keys.includes(key);\n")
	builder.WriteString("}\n\n")
	builder.WriteString("const atlasProtocolPatternCache = new Map<string, RegExp>();\n\n")
	builder.WriteString("function atlasProtocolStringMatches(value: string, pattern: string): boolean {\n")
	builder.WriteString("  let expression = atlasProtocolPatternCache.get(pattern);\n")
	builder.WriteString("  if (!expression) {\n")
	builder.WriteString("    expression = new RegExp(pattern);\n")
	builder.WriteString("    atlasProtocolPatternCache.set(pattern, expression);\n")
	builder.WriteString("  }\n")
	builder.WriteString("  return expression.test(value);\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolKeyMatches(key: string, pattern: string): boolean {\n")
	builder.WriteString("  return atlasProtocolStringMatches(key, pattern);\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolIsRecord(value: unknown): value is Record<string, unknown> {\n")
	builder.WriteString("  if (typeof value !== \"object\" || value === null || Array.isArray(value)) {\n")
	builder.WriteString("    return false;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  const prototype = Object.getPrototypeOf(value);\n")
	builder.WriteString("  if (prototype === null) {\n")
	builder.WriteString("    return true;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  let basePrototype = prototype;\n")
	builder.WriteString("  while (Object.getPrototypeOf(basePrototype) !== null) {\n")
	builder.WriteString("    basePrototype = Object.getPrototypeOf(basePrototype);\n")
	builder.WriteString("  }\n")
	builder.WriteString("  return prototype === basePrototype;\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolIsNonEmptyString(value: unknown): value is string {\n")
	builder.WriteString("  return typeof value === \"string\" && value.trim() !== \"\";\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolIsRFC3339String(value: unknown): value is string {\n")
	builder.WriteString("  if (typeof value !== \"string\") {\n")
	builder.WriteString("    return false;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  const match = /^(\\d{4})-(\\d{2})-(\\d{2})T(\\d{2}):(\\d{2}):(\\d{2})(?:\\.\\d+)?(Z|[+-]\\d{2}:\\d{2})$/.exec(value);\n")
	builder.WriteString("  if (!match || !Number.isFinite(Date.parse(value))) {\n")
	builder.WriteString("    return false;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  const year = Number(match[1]);\n")
	builder.WriteString("  const month = Number(match[2]);\n")
	builder.WriteString("  const day = Number(match[3]);\n")
	builder.WriteString("  const hour = Number(match[4]);\n")
	builder.WriteString("  const minute = Number(match[5]);\n")
	builder.WriteString("  const second = Number(match[6]);\n")
	builder.WriteString("  const zone = match[7];\n")
	builder.WriteString("  if (month < 1 || month > 12 || day < 1 || day > atlasProtocolDaysInMonth(year, month)) {\n")
	builder.WriteString("    return false;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  if (hour > 23 || minute > 59 || second > 59) {\n")
	builder.WriteString("    return false;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  if (zone !== \"Z\") {\n")
	builder.WriteString("    const zoneHour = Number(zone.slice(1, 3));\n")
	builder.WriteString("    const zoneMinute = Number(zone.slice(4, 6));\n")
	builder.WriteString("    if (zoneHour > 23 || zoneMinute > 59) {\n")
	builder.WriteString("      return false;\n")
	builder.WriteString("    }\n")
	builder.WriteString("  }\n")
	builder.WriteString("  return true;\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolDaysInMonth(year: number, month: number): number {\n")
	builder.WriteString("  if (month === 2) {\n")
	builder.WriteString("    return year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0) ? 29 : 28;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  return [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][month - 1];\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolIsJSONValue(value: unknown): value is JSONValue {\n")
	builder.WriteString("  return atlasProtocolIsJSONValueInternal(value, new WeakSet<object>());\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolIsJSONValueInternal(value: unknown, seen: WeakSet<object>): value is JSONValue {\n")
	builder.WriteString("  if (value === null) {\n")
	builder.WriteString("    return true;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  switch (typeof value) {\n")
	builder.WriteString("    case \"boolean\":\n")
	builder.WriteString("    case \"string\":\n")
	builder.WriteString("      return true;\n")
	builder.WriteString("    case \"number\":\n")
	builder.WriteString("      return Number.isFinite(value);\n")
	builder.WriteString("    case \"object\":\n")
	builder.WriteString("      if (seen.has(value)) {\n")
	builder.WriteString("        return false;\n")
	builder.WriteString("      }\n")
	builder.WriteString("      seen.add(value);\n")
	builder.WriteString("      if (Array.isArray(value)) {\n")
	builder.WriteString("        const valid = value.every((item) => atlasProtocolIsJSONValueInternal(item, seen));\n")
	builder.WriteString("        seen.delete(value);\n")
	builder.WriteString("        return valid;\n")
	builder.WriteString("      }\n")
	builder.WriteString("      const valid = atlasProtocolIsRecord(value) && Object.values(value).every((item) => atlasProtocolIsJSONValueInternal(item, seen));\n")
	builder.WriteString("      seen.delete(value);\n")
	builder.WriteString("      return valid;\n")
	builder.WriteString("    default:\n")
	builder.WriteString("      return false;\n")
	builder.WriteString("  }\n")
	builder.WriteString("}\n\n")
	return builder.String()
}
