package artifacts

import (
	"strconv"
	"strings"

	protocolvalidator "github.com/the-drunken-coder/atlas/atlas_protocol/validator"
)

func runtimeValidatorHelpersSource() string {
	var builder strings.Builder
	builder.WriteString("function atlasProtocolHasOwn(value: Record<string, unknown>, key: string): boolean {\n")
	builder.WriteString("  return Object.prototype.hasOwnProperty.call(value, key);\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolKnownKeys(keys: readonly string[], key: string): boolean {\n")
	builder.WriteString("  return keys.includes(key);\n")
	builder.WriteString("}\n\n")
	builder.WriteString("const atlasProtocolPatternCache = new Map<string, RegExp>();\n\n")
	builder.WriteString("function atlasProtocolStringMatches(value: string, pattern: string): boolean {\n")
	builder.WriteString("  let expression = atlasProtocolPatternCache.get(pattern);\n")
	builder.WriteString("  if (!expression) {\n")
	builder.WriteString("    expression = new RegExp(pattern);\n")
	builder.WriteString("    atlasProtocolPatternCache.set(pattern, expression);\n")
	builder.WriteString("  }\n")
	builder.WriteString("  return expression.test(value);\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolKeyMatches(key: string, pattern: string): boolean {\n")
	builder.WriteString("  return atlasProtocolStringMatches(key, pattern);\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolIsRecord(value: unknown): value is Record<string, unknown> {\n")
	builder.WriteString("  if (typeof value !== \"object\" || value === null || Array.isArray(value)) {\n")
	builder.WriteString("    return false;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  const prototype = Object.getPrototypeOf(value);\n")
	builder.WriteString("  if (prototype === null) {\n")
	builder.WriteString("    return true;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  return Object.getPrototypeOf(prototype) === null;\n")
	builder.WriteString("}\n\n")
	builder.WriteString("const atlasProtocolMaxGeometryPositions = ")
	builder.WriteString(strconv.Itoa(protocolvalidator.MaxGeometryPositions))
	builder.WriteString(";\n\n")
	builder.WriteString("function atlasProtocolHasValidPolygonSemantics(value: unknown): boolean {\n")
	builder.WriteString("  if (!atlasProtocolIsRecord(value) || value[\"type\"] !== \"Polygon\" || !Array.isArray(value[\"coordinates\"])) {\n")
	builder.WriteString("    return false;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  let totalPositions = 0;\n")
	builder.WriteString("  for (const ring of value[\"coordinates\"]) {\n")
	builder.WriteString("    if (!Array.isArray(ring) || ring.length < 2 || !atlasProtocolPositionsEqual(ring[0], ring[ring.length - 1])) {\n")
	builder.WriteString("      return false;\n")
	builder.WriteString("    }\n")
	builder.WriteString("    totalPositions += ring.length;\n")
	builder.WriteString("    if (totalPositions > atlasProtocolMaxGeometryPositions) {\n")
	builder.WriteString("      return false;\n")
	builder.WriteString("    }\n")
	builder.WriteString("  }\n")
	builder.WriteString("  return true;\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolPositionsEqual(left: unknown, right: unknown): boolean {\n")
	builder.WriteString("  return Array.isArray(left) && Array.isArray(right) && left.length === right.length && left.every((item, index) => item === right[index]);\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolHasValidCommandCatalogSemantics(value: unknown): boolean {\n")
	builder.WriteString("  if (!Array.isArray(value)) return false;\n")
	builder.WriteString("  const commandIDs = new Set<string>();\n")
	builder.WriteString("  for (const command of value) {\n")
	builder.WriteString("    if (!atlasProtocolIsRecord(command) || typeof command[\"command\"] !== \"string\") return false;\n")
	builder.WriteString("    if (commandIDs.has(command[\"command\"])) return false;\n")
	builder.WriteString("    commandIDs.add(command[\"command\"]);\n")
	builder.WriteString("  }\n")
	builder.WriteString("  return true;\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolIsNonEmptyString(value: unknown): value is string {\n")
	builder.WriteString("  return typeof value === \"string\" && value.trim() !== \"\";\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolIsRFC3339String(value: unknown): value is string {\n")
	builder.WriteString("  if (typeof value !== \"string\") {\n")
	builder.WriteString("    return false;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  const match = /^(\\d{4})-(\\d{2})-(\\d{2})T(\\d{2}):(\\d{2}):(\\d{2})(?:\\.\\d+)?(Z|[+-]\\d{2}:\\d{2})$/.exec(value);\n")
	builder.WriteString("  if (!match || !Number.isFinite(Date.parse(value))) {\n")
	builder.WriteString("    return false;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  const year = Number(match[1]);\n")
	builder.WriteString("  const month = Number(match[2]);\n")
	builder.WriteString("  const day = Number(match[3]);\n")
	builder.WriteString("  const hour = Number(match[4]);\n")
	builder.WriteString("  const minute = Number(match[5]);\n")
	builder.WriteString("  const second = Number(match[6]);\n")
	builder.WriteString("  const zone = match[7];\n")
	builder.WriteString("  if (month < 1 || month > 12 || day < 1 || day > atlasProtocolDaysInMonth(year, month)) {\n")
	builder.WriteString("    return false;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  if (hour > 23 || minute > 59 || second > 59) {\n")
	builder.WriteString("    return false;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  if (zone !== \"Z\") {\n")
	builder.WriteString("    const zoneHour = Number(zone.slice(1, 3));\n")
	builder.WriteString("    const zoneMinute = Number(zone.slice(4, 6));\n")
	builder.WriteString("    if (zoneHour > 23 || zoneMinute > 59) {\n")
	builder.WriteString("      return false;\n")
	builder.WriteString("    }\n")
	builder.WriteString("  }\n")
	builder.WriteString("  return true;\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolDaysInMonth(year: number, month: number): number {\n")
	builder.WriteString("  if (month === 2) {\n")
	builder.WriteString("    return year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0) ? 29 : 28;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  return [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][month - 1];\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolIsJSONValue(value: unknown): value is JSONValue {\n")
	builder.WriteString("  type WorkItem = { value: unknown } | { leave: object };\n")
	builder.WriteString("  const active = new WeakSet<object>();\n")
	builder.WriteString("  const work: WorkItem[] = [{ value }];\n")
	builder.WriteString("  while (work.length > 0) {\n")
	builder.WriteString("    const item = work.pop()!;\n")
	builder.WriteString("    if (\"leave\" in item) {\n")
	builder.WriteString("      active.delete(item.leave);\n")
	builder.WriteString("      continue;\n")
	builder.WriteString("    }\n")
	builder.WriteString("    const current = item.value;\n")
	builder.WriteString("    if (current === null || typeof current === \"boolean\" || typeof current === \"string\") {\n")
	builder.WriteString("      continue;\n")
	builder.WriteString("    }\n")
	builder.WriteString("    if (typeof current === \"number\") {\n")
	builder.WriteString("      if (!Number.isFinite(current)) return false;\n")
	builder.WriteString("      continue;\n")
	builder.WriteString("    }\n")
	builder.WriteString("    if (typeof current !== \"object\" || (!Array.isArray(current) && !atlasProtocolIsJSONRecord(current))) {\n")
	builder.WriteString("      return false;\n")
	builder.WriteString("    }\n")
	builder.WriteString("    if (Array.isArray(current) && !atlasProtocolHasOnlyArrayEntries(current)) return false;\n")
	builder.WriteString("    if (active.has(current)) return false;\n")
	builder.WriteString("    active.add(current);\n")
	builder.WriteString("    work.push({ leave: current });\n")
	builder.WriteString("    const children = Array.isArray(current)\n")
	builder.WriteString("      ? Array.from({ length: current.length }, (_, index) => current[index])\n")
	builder.WriteString("      : Object.values(current);\n")
	builder.WriteString("    for (let index = children.length - 1; index >= 0; index--) {\n")
	builder.WriteString("      work.push({ value: children[index] });\n")
	builder.WriteString("    }\n")
	builder.WriteString("  }\n")
	builder.WriteString("  return true;\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolIsJSONRecord(value: object): value is Record<string, unknown> {\n")
	builder.WriteString("  const prototype = Object.getPrototypeOf(value);\n")
	builder.WriteString("  if (\n")
	builder.WriteString("    prototype !== null &&\n")
	builder.WriteString("    (Object.getPrototypeOf(prototype) !== null ||\n")
	builder.WriteString("      Reflect.ownKeys(prototype).some((key) => Reflect.getOwnPropertyDescriptor(prototype, key)?.enumerable))\n")
	builder.WriteString("  ) {\n")
	builder.WriteString("    return false;\n")
	builder.WriteString("  }\n")
	builder.WriteString("  return Reflect.ownKeys(value).every(\n")
	builder.WriteString("    (key) => typeof key === \"string\" && Reflect.getOwnPropertyDescriptor(value, key)?.enumerable === true\n")
	builder.WriteString("  );\n")
	builder.WriteString("}\n\n")
	builder.WriteString("function atlasProtocolHasOnlyArrayEntries(value: unknown[]): boolean {\n")
	builder.WriteString("  return Reflect.ownKeys(value).every((key) => {\n")
	builder.WriteString("    if (key === \"length\") return true;\n")
	builder.WriteString("    if (typeof key !== \"string\") return false;\n")
	builder.WriteString("    const index = Number(key);\n")
	builder.WriteString("    return Number.isInteger(index) && index >= 0 && index < value.length && String(index) === key;\n")
	builder.WriteString("  });\n")
	builder.WriteString("}\n\n")
	return builder.String()
}
