export {
  AtlasAPIError,
  AtlasClient,
  type AtlasClientOptions,
  type AtlasLocalDeleteWatchEvent,
  type AtlasRecoveredWatchEvent,
  type AtlasSubscription,
  type AtlasWatchEvent,
  type ChangedSinceQueryOptions,
  type ChangedSinceResponse,
  ConflictError,
  type EntityCheckInFields,
  type EntityCheckInMethod,
  type EntityCheckInMinimalTask,
  type EntityCheckInOptions,
  type EntityCheckInResponse,
  type EntityCheckInTelemetry,
  type FullDatasetQueryOptions,
  type FullDatasetResponse,
  ProtocolMismatchError,
  type ReadOptions,
  type SyncSnapshot,
  type SyncStatus,
  type TaskCompleteOptions,
  type TaskFailOptions,
  type TaskLifecycleOptions,
  type TaskStatus,
  type TaskStatusOptions
} from "./client.js";
export { type ErrorMessageSanitizerOptions, sanitizeErrorMessage } from "./error-sanitizer.js";
export type {
  EntityComponents,
  EntityCreateRequest,
  EntityResource,
  EntityUpdateRequest,
  ErrorCode,
  ErrorResponse,
  FeedEvent,
  JSONValue,
  ObjectCreateRequest,
  ObjectDetailResource,
  ObjectResource,
  ObjectUpdateRequest,
  ResourceType,
  TaskCreateRequest,
  TaskResource,
  TaskUpdateRequest
} from "./protocol.js";
export {
  ATLAS_PROTOCOL_REVISION,
  isEntityCreateRequest,
  isEntityUpdateRequest,
  isObjectCreateRequest,
  isObjectUpdateRequest,
  isTaskCreateRequest,
  isTaskUpdateRequest
} from "./protocol.js";
