#!/usr/bin/env python3
"""
ATLAS Core System - Docker Container Management

Simple script to start Docker containers for the ATLAS Core System.

Usage:
    python atlas.py              # Interactive menu to choose startup options
    python atlas.py --tunnel     # Start all containers with Cloudflare tunnel (non-interactive)
    python atlas.py --db-only    # Start only PostgreSQL container (non-interactive)
    python atlas.py --help       # Show help
"""

import argparse
import logging
import os
import re
import secrets
import subprocess
import sys
import time

try:
    from .compose_env import load_compose_dotenv
    from .seed_command_catalog import publish_command_catalog
except ImportError:
    from compose_env import load_compose_dotenv
    from seed_command_catalog import publish_command_catalog

logger = logging.getLogger(__name__)

API_AUTH_KEY_PLACEHOLDER = "REPLACE_WITH_SECURE_KEY"
DEFAULT_TUNNEL_HOSTNAME = "atlascommandapi.org"
TUNNEL_HOSTNAME_ENV = "ATLAS_TUNNEL_HOSTNAME"
COMPOSE_ENV_BARE_VALUE_RE = re.compile(r"^[A-Za-z0-9_./:@%+=,-]+$")


def print_banner():
    """Print the ATLAS banner."""
    banner = """
===============================================================
                    ATLAS Core System
                   Docker Container Manager
===============================================================
    """
    print(banner)


def ensure_minio_secrets():
    """Generate ephemeral MinIO secrets if they are not set."""
    created = []
    generated_values = {}
    root_password = os.getenv("MINIO_ROOT_PASSWORD")
    secret_key = os.getenv("MINIO_SECRET_KEY")
    root_user = os.getenv("MINIO_ROOT_USER")
    access_key = os.getenv("MINIO_ACCESS_KEY")

    if not root_user:
        os.environ["MINIO_ROOT_USER"] = "atlas"
        generated_values["MINIO_ROOT_USER"] = "atlas"
        created.append("MINIO_ROOT_USER")
        root_user = "atlas"

    if not root_password and not secret_key:
        generated = secrets.token_urlsafe(32)
        os.environ["MINIO_ROOT_PASSWORD"] = generated
        os.environ["MINIO_SECRET_KEY"] = generated
        generated_values["MINIO_ROOT_PASSWORD"] = generated
        generated_values["MINIO_SECRET_KEY"] = generated
        created.extend(["MINIO_ROOT_PASSWORD", "MINIO_SECRET_KEY"])
    elif not root_password and secret_key:
        os.environ["MINIO_ROOT_PASSWORD"] = secret_key
        created.append("MINIO_ROOT_PASSWORD")
    elif root_password and not secret_key:
        os.environ["MINIO_SECRET_KEY"] = root_password
        created.append("MINIO_SECRET_KEY")

    if root_user and not access_key:
        os.environ["MINIO_ACCESS_KEY"] = root_user
        if "MINIO_ROOT_USER" in generated_values:
            generated_values["MINIO_ACCESS_KEY"] = root_user
        created.append("MINIO_ACCESS_KEY")

    if created:
        print(f"[INFO] Set MinIO credentials for this run: {', '.join(created)}")
    return generated_values


def ensure_postgres_password():
    """Ensure POSTGRES_PASSWORD is set (generate one if missing)."""
    if not os.getenv("POSTGRES_PASSWORD"):
        generated = secrets.token_urlsafe(24)
        os.environ["POSTGRES_PASSWORD"] = generated
        print("[INFO] Generated POSTGRES_PASSWORD for this run (redacted)")
        return {"POSTGRES_PASSWORD": generated}
    return {}


def compose_env_key(line):
    """Return the key assigned by a Compose .env line, if any."""
    stripped = line.strip()
    if not stripped or stripped.startswith("#"):
        return None
    if stripped.startswith("export "):
        stripped = stripped[len("export ") :].strip()

    separator_indexes = [index for index in (stripped.find("="), stripped.find(":")) if index != -1]
    if not separator_indexes:
        return None
    separator_index = min(separator_indexes)
    key = stripped[:separator_index].strip()
    return key or None


def format_compose_env_value(value):
    """Format a generated value for a Docker Compose .env file."""
    if COMPOSE_ENV_BARE_VALUE_RE.fullmatch(value):
        return value
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def persist_compose_env_values(docker_dir, values):
    """Persist generated/defaulted values to docker/.env without duplicating keys."""
    if not values:
        return

    env_path = os.path.join(docker_dir, ".env")
    lines = []
    if os.path.exists(env_path):
        with open(env_path, "r", encoding="utf-8") as env_file:
            lines = env_file.readlines()
    else:
        lines = [
            "# Generated by Atlas Core atlas.py for local Docker Compose runs.\n",
            "# Values here are local scratch-runtime credentials; rotate freely.\n",
        ]

    written = set()
    updated_lines = []
    for line in lines:
        key = compose_env_key(line)
        if key in values:
            updated_lines.append(f"{key}={format_compose_env_value(values[key])}\n")
            written.add(key)
        else:
            updated_lines.append(line)

    if updated_lines and updated_lines[-1].strip():
        updated_lines.append("\n")

    for key in sorted(set(values) - written):
        updated_lines.append(f"{key}={format_compose_env_value(values[key])}\n")

    with open(env_path, "w", encoding="utf-8") as env_file:
        env_file.writelines(updated_lines)
    try:
        os.chmod(env_path, 0o600)
    except OSError as exc:
        logger.debug("Could not chmod %s: %s", env_path, exc)

    keys = ", ".join(sorted(values))
    print(f"[INFO] Persisted generated Docker Compose values to {env_path}: {keys}")


def resolve_atlas_core_dir():
    """Return the absolute path to the Atlas_Core directory."""
    current_dir = os.path.abspath(os.path.dirname(__file__))
    search_dir = current_dir
    while True:
        if os.path.basename(search_dir) == "Atlas_Core":
            return search_dir
        candidate = os.path.join(search_dir, "Atlas_Core")
        if os.path.isdir(candidate):
            return candidate
        parent = os.path.dirname(search_dir)
        if parent == search_dir:
            break
        search_dir = parent
    raise FileNotFoundError("Atlas_Core directory not found")


def database_recreate_on_startup_enabled():
    """Return whether startup will use recreate mode by default."""
    raw = os.getenv("DATABASE_RECREATE_ON_STARTUP", "true").strip().lower()
    return raw not in {"false", "0", "no", "off"}


def print_disposable_storage_notice(db_only=False):
    """Print Atlas Core's runtime-storage posture before startup."""
    if db_only:
        return
    if database_recreate_on_startup_enabled():
        print(
            "[WARN] Atlas Core runtime storage is disposable: startup drops and "
            "recreates PostgreSQL tables and clears the configured MinIO bucket."
        )
        return
    print(
        "[INFO] DATABASE_RECREATE_ON_STARTUP=false; PostgreSQL and the configured "
        "MinIO bucket remain scratch runtime storage, not durable systems of record."
    )


def wait_for_database_docker(container_name="atlas_core_postgres", max_retries=30, delay=1.0):
    """Wait for PostgreSQL to be ready using docker exec pg_isready."""
    print("[WAIT] Waiting for PostgreSQL to be ready...")
    password = os.getenv("POSTGRES_PASSWORD", "")

    for attempt in range(max_retries):
        try:
            cmd = [
                "docker",
                "exec",
            ]
            if password:
                cmd.extend(["-e", f"PGPASSWORD={password}"])
            cmd.extend(
                [
                    container_name,
                    "pg_isready",
                    "-U",
                    "atlas",
                    "-d",
                    "atlas_core",
                ]
            )
            result = subprocess.run(
                cmd,
                capture_output=True,
                timeout=5,
            )
            if result.returncode == 0:
                print("[OK] PostgreSQL is ready!")
                return True
        except subprocess.TimeoutExpired:
            pass  # Treat timeout as a failed attempt, continue retrying

        if attempt < max_retries - 1:
            print(f"[WAIT] Database not ready (attempt {attempt + 1}/{max_retries}), retrying...")
            time.sleep(delay)

    raise Exception(f"PostgreSQL not ready after {max_retries} attempts")


def wait_for_minio(container_name="atlas_core_minio", max_retries=30, delay=1.0):
    """Wait for MinIO to be ready using docker exec mc ready."""
    print("[WAIT] Waiting for MinIO to be ready...")

    for attempt in range(max_retries):
        try:
            result = subprocess.run(
                ["docker", "exec", container_name, "mc", "ready", "local"],
                capture_output=True,
                timeout=5,
            )
            if result.returncode == 0:
                print("[OK] MinIO is ready!")
                return True
        except subprocess.TimeoutExpired:
            pass  # Treat timeout as a failed attempt, continue retrying

        if attempt < max_retries - 1:
            print(f"[WAIT] MinIO not ready (attempt {attempt + 1}/{max_retries}), retrying...")
            time.sleep(delay)

    raise Exception(f"MinIO not ready after {max_retries} attempts")


def cleanup_init_containers():
    """Remove one-shot init containers after they complete."""
    init_containers = ["atlas_core_minio_init"]

    for container in init_containers:
        try:
            # Check if container exists and is exited
            result = subprocess.run(
                [
                    "docker",
                    "ps",
                    "-a",
                    "--filter",
                    f"name={container}",
                    "--filter",
                    "status=exited",
                    "-q",
                ],
                capture_output=True,
                text=True,
                timeout=5,
            )
            if result.stdout.strip():
                # Container exists and is exited, remove it
                subprocess.run(
                    ["docker", "rm", container],
                    capture_output=True,
                    timeout=5,
                )
                print(f"[CLEANUP] Removed init container: {container}")
        except subprocess.TimeoutExpired as exc:
            logger.debug("Timeout during container cleanup: %s", exc)
        except Exception as exc:
            logger.debug("Error during container cleanup: %s", exc)


def wait_for_api(max_retries=30, delay=2.0):
    """Wait for the API to be ready."""
    print("[WAIT] Waiting for API to be ready...")

    for attempt in range(max_retries):
        try:
            result = subprocess.run(
                [
                    "docker",
                    "exec",
                    "atlas_core_api",
                    "curl",
                    "-sf",
                    "--connect-timeout",
                    "3",
                    "--max-time",
                    "5",
                    "http://localhost:8000/health",
                ],
                capture_output=True,
                timeout=5,
            )
            if result.returncode == 0:
                print("[OK] API is ready!")
                return True
        except subprocess.TimeoutExpired:
            pass  # Treat timeout as a failed attempt, continue retrying

        if attempt < max_retries - 1:
            print(f"[WAIT] API not ready (attempt {attempt + 1}/{max_retries}), retrying...")
            time.sleep(delay)

    raise Exception(f"API not ready after {max_retries} attempts")


def ensure_minio_bucket_docker(container_name="atlas_core_minio", bucket="atlas-media"):
    """Ensure the MinIO bucket exists using mc client.

    Note: The Go service also ensures the bucket exists on startup,
    but this provides an early check during container initialization.
    """
    print(f"[BUILD] Ensuring MinIO bucket exists: {bucket}")

    # The minio-init container in docker compose handles bucket creation,
    # but we verify it here as a fallback
    try:
        result = subprocess.run(
            ["docker", "exec", container_name, "mc", "stat", f"local/{bucket}"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            print("[OK] MinIO bucket ready!")
            return
    except subprocess.TimeoutExpired:
        pass
    except Exception as e:
        print(f"[WARN] Could not verify MinIO bucket: {e}")

    # Bucket creation is handled by minio-init container in docker compose
    print("[OK] MinIO bucket initialization delegated to minio-init container!")


def wait_for_database_schema_docker(container_name="atlas_core_postgres", max_retries=60, delay=2.0):
    """Wait until the Go API has run EnsureTables (schema authority: internal/database/db.go)."""
    print("[WAIT] Waiting for database schema (EnsureTables)...")
    password = os.getenv("POSTGRES_PASSWORD", "")
    check_sql = (
        "SELECT 1 FROM information_schema.tables "
        "WHERE table_schema = 'public' AND table_name = 'entities'"
    )

    for attempt in range(max_retries):
        try:
            cmd = ["docker", "exec"]
            if password:
                cmd.extend(["-e", f"PGPASSWORD={password}"])
            cmd.extend(
                [
                    container_name,
                    "psql",
                    "-U",
                    "atlas",
                    "-d",
                    "atlas_core",
                    "-tAc",
                    check_sql,
                ]
            )
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode == 0 and result.stdout.strip() == "1":
                print("[OK] Database schema ready!")
                return True
        except subprocess.TimeoutExpired:
            pass

        if attempt < max_retries - 1:
            print(
                f"[WAIT] Schema not ready (attempt {attempt + 1}/{max_retries}), retrying..."
            )
            time.sleep(delay)

    raise Exception(f"Database schema not ready after {max_retries} attempts")


def cleanup_containers(atlas_core_dir, remove_volumes=False):
    """Stop containers and optionally delete related volumes/images."""
    print("[STOP] Stopping existing containers...")
    docker_dir = os.path.join(atlas_core_dir, "docker")
    cmd = ["docker", "compose", "down", "--remove-orphans"]
    if remove_volumes:
        print("[STOP] Removing container volumes and local images...")
        cmd.extend(["--volumes", "--rmi", "local"])
    result = subprocess.run(
        cmd,
        cwd=docker_dir,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        msg = f"docker compose down failed (exit {result.returncode})"
        logger.error(msg)
        out = (result.stdout or "").strip()
        err = (result.stderr or "").strip()
        if out:
            logger.error("docker compose down stdout:\n%s", out)
        if err:
            logger.error("docker compose down stderr:\n%s", err)
        detail = err or out
        raise RuntimeError(f"{msg}" + (f": {detail}" if detail else ""))


def ensure_tunnel_token():
    """Ensure tunnel startup has a Cloudflare tunnel token."""
    token = os.getenv("CLOUDFLARE_TUNNEL_TOKEN")
    if token:
        print("[INFO] Using CLOUDFLARE_TUNNEL_TOKEN from environment.")
        return True

    print("[WARN] Tunnel mode requires CLOUDFLARE_TUNNEL_TOKEN.")
    return False


def ensure_tunnel_api_auth():
    """Ensure public tunnel mode cannot start with development auth defaults."""
    api_auth_key = os.getenv("API_AUTH_KEY", "").strip()
    if not api_auth_key:
        print("[ERROR] Tunnel mode requires API_AUTH_KEY to be set.")
        return False
    if api_auth_key == API_AUTH_KEY_PLACEHOLDER:
        print("[ERROR] Tunnel mode requires a real API_AUTH_KEY, not the example placeholder.")
        return False

    os.environ["ENABLE_API_AUTH"] = "true"
    return True


def tunnel_public_base_url():
    """Return the configured public tunnel base URL."""
    hostname = os.getenv(TUNNEL_HOSTNAME_ENV, DEFAULT_TUNNEL_HOSTNAME).strip()
    if not hostname:
        hostname = DEFAULT_TUNNEL_HOSTNAME
    if "://" in hostname:
        return hostname.rstrip("/")
    return f"https://{hostname.strip('/')}"


def tunnel_health_url():
    """Return the configured public tunnel health URL."""
    return f"{tunnel_public_base_url()}/health"


def verify_tunnel_connection(
    public_url=None, max_retries=10, delay=2.0
):
    """Verify the Cloudflare tunnel is working by checking the public health endpoint."""
    import urllib.request
    import urllib.error
    import urllib.parse
    import json

    if public_url is None:
        public_url = tunnel_health_url()

    print("[WAIT] Verifying Cloudflare tunnel connection...")
    parsed = urllib.parse.urlparse(public_url)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        print("[WARN] Invalid public URL for tunnel verification")
        return False, "Invalid tunnel verification URL"

    for attempt in range(max_retries):
        try:
            req = urllib.request.Request(public_url, headers={"User-Agent": "ATLAS-Startup"})
            # nosemgrep: python.lang.security.audit.dynamic-urllib-use-detected.dynamic-urllib-use-detected
            with urllib.request.urlopen(req, timeout=10) as response:
                data = json.loads(response.read().decode())
                if data.get("status") == "healthy":
                    print("[OK] Cloudflare tunnel verified - public endpoint is accessible!")
                    return True, "Connected and healthy"
        except urllib.error.HTTPError as e:
            logger.debug("Tunnel verification HTTP error: %s", e)
            # A warming tunnel commonly returns 5xx (e.g. Cloudflare 502/503/504)
            # before the origin is reachable, so keep retrying on server errors.
            if e.code >= 500:
                pass  # Tunnel still warming up, retry
            else:
                return False, f"HTTP {e.code}"
        except urllib.error.URLError:
            pass  # Network error, retry
        except json.JSONDecodeError:
            # A warming tunnel may serve a non-JSON HTML error page; keep retrying.
            logger.debug("Tunnel verification got non-JSON response, retrying")
            pass
        except Exception as exc:
            logger.debug("Tunnel verification attempt failed: %s", exc)  # Other error, retry

        if attempt < max_retries - 1:
            print(f"[WAIT] Tunnel not ready (attempt {attempt + 1}/{max_retries}), retrying...")
            time.sleep(delay)

    print("[WARN] Could not verify tunnel - may still be connecting")
    return False, "Connection not verified (may still be starting)"


def start_containers(db_only=False, tunnel=False, reset_volumes=False):
    """Start Docker containers using docker compose."""
    print_banner()

    try:
        atlas_core_dir = resolve_atlas_core_dir()
        docker_dir = os.path.join(atlas_core_dir, "docker")
        load_compose_dotenv(docker_dir)
        generated_compose_values = {}
        generated_compose_values.update(ensure_minio_secrets())
        generated_compose_values.update(ensure_postgres_password())
        persist_compose_env_values(docker_dir, generated_compose_values)
        print_disposable_storage_notice(db_only=db_only)

        if tunnel:
            if not ensure_tunnel_token():
                sys.exit(1)
            if not ensure_tunnel_api_auth():
                sys.exit(1)

        cleanup_containers(atlas_core_dir, remove_volumes=reset_volumes)

        if db_only:
            print("[START] Starting PostgreSQL container...")
            subprocess.run(
                ["docker", "compose", "up", "-d", "--build", "postgres"],
                check=True,
                cwd=docker_dir,
            )
            print("[OK] PostgreSQL container started successfully!")
        elif tunnel:
            print("[START] Starting all containers with Cloudflare tunnel...")
            subprocess.run(
                [
                    "docker",
                    "compose",
                    "-f",
                    "docker-compose.yml",
                    "-f",
                    "docker-compose.tunnel.yml",
                    "up",
                    "-d",
                    "--build",
                ],
                check=True,
                cwd=docker_dir,
            )
            print("[OK] All containers with Cloudflare tunnel started successfully!")
        else:
            print("[START] Starting all containers (PostgreSQL, MinIO, API)...")
            subprocess.run(
                ["docker", "compose", "up", "-d", "--build"],
                check=True,
                cwd=docker_dir,
            )
            print("[OK] All containers started successfully!")

        wait_for_database_docker()

        if not db_only:
            wait_for_minio()
            ensure_minio_bucket_docker()
            cleanup_init_containers()
            wait_for_api()
            wait_for_database_schema_docker()
        else:
            print(
                "[INFO] --db-only: schema is created when the API starts (EnsureTables in db.go)"
            )

        print("\n" + "=" * 60)
        print("ATLAS Core System - Connection Information")
        print("=" * 60)

        if not db_only:
            print("\nAPI:")
            print("  HTTP:   http://localhost:8000")
            print("  Health: http://localhost:8000/health")

        print("\nPostgreSQL:")
        print("  Host:     localhost (or 127.0.0.1)")
        print("  Port:     5432")
        print("  Database: atlas_core")
        print("  User:     atlas")
        if os.getenv("POSTGRES_PASSWORD"):
            print("  Password: **** (set, redacted)")
        else:
            print("  Password: (set POSTGRES_PASSWORD)")
        print("  URL:      postgresql://atlas:<POSTGRES_PASSWORD>@localhost:5432/atlas_core")

        if not db_only:
            print("\nMinIO (Object Storage):")
            print("  API:      http://localhost:9000")
            print("  Console:  http://localhost:9001")
            print("  User:     atlas")
            print("  Password: *****")
            print("  Bucket:   atlas-media")

        if tunnel:
            tunnel_verified, tunnel_status = verify_tunnel_connection()
            print("\nCloudflare Tunnel:")
            print(f"  Public URL: {tunnel_public_base_url()}")
            if tunnel_verified:
                print(f"  Status:     [OK] {tunnel_status}")
            else:
                print(f"  Status:     [WARN] {tunnel_status}")

        print("=" * 60)
        if not db_only and not publish_command_catalog():
            print("[ERROR] Failed to publish command catalog")
            sys.exit(1)

    except subprocess.CalledProcessError as e:
        print(f"[ERROR] Failed to start containers: {e}")
        sys.exit(1)
    except FileNotFoundError as e:
        print(f"[ERROR] {e}")
        sys.exit(1)
    except KeyboardInterrupt:
        print("\n[STOP] Startup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"[ERROR] {e}")
        sys.exit(1)


def show_interactive_menu():
    """Display interactive menu and return user selection."""
    print("\n" + "=" * 60)
    print("ATLAS Core System - Startup Options")
    print("=" * 60 + "\n")
    print("Select startup option:")
    print("  1. Start all containers (PostgreSQL, MinIO, API) - Default")
    print("  2. Start all containers with Cloudflare tunnel")
    print("\n" + "-" * 60)

    while True:
        try:
            choice = input("Enter your choice (1-2) [default: 1]: ").strip()

            # Default to option 1 if empty
            if not choice:
                choice = "1"

            if choice == "1":
                return (False, False)  # (db_only, tunnel)
            elif choice == "2":
                return (False, True)  # (db_only, tunnel)
            else:
                print(f"[ERROR] Invalid choice: {choice}. Please enter 1 or 2.")
        except KeyboardInterrupt:
            print("\n\n[EXIT] Cancelled by user")
            sys.exit(0)
        except EOFError:
            print("\n\n[EXIT] Cancelled by user")
            sys.exit(0)


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="ATLAS Core System - Docker Container Manager",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python atlas.py              # Interactive menu to choose startup options
  python atlas.py --tunnel     # Start all containers with Cloudflare tunnel (non-interactive)
  python atlas.py --db-only    # Start only PostgreSQL container (non-interactive)
        """,
    )

    parser.add_argument(
        "--db-only",
        action="store_true",
        help="Start only the PostgreSQL container (skip API and MinIO)",
    )

    parser.add_argument(
        "--tunnel",
        action="store_true",
        help="Start all containers with Cloudflare tunnel for public HTTPS access",
    )
    parser.add_argument(
        "--reset-volumes",
        action="store_true",
        help="Remove local Docker volumes and images before starting",
    )

    args = parser.parse_args()

    if args.db_only and args.tunnel:
        print("[ERROR] Cannot use --db-only and --tunnel together")
        sys.exit(1)

    # Interactive menu only when invoked with no flags (any flag => non-interactive).
    if not (args.db_only or args.tunnel or args.reset_volumes):
        db_only, tunnel = show_interactive_menu()
    else:
        db_only = args.db_only
        tunnel = args.tunnel

    start_containers(db_only=db_only, tunnel=tunnel, reset_volumes=args.reset_volumes)


if __name__ == "__main__":
    main()
