"""Small Docker Compose .env parser used by atlas.py startup preflight."""

from __future__ import annotations

import os
import re
import tempfile
from collections.abc import Callable, MutableMapping

COMPOSE_ENV_BARE_VALUE_RE = re.compile(r"^[A-Za-z0-9_./:@%+=,-]+$")
COMPOSE_ENV_CONTROL_CHAR_RE = re.compile(r"[\x00-\x1F\x7F]")


def parse_compose_env_file(env_path: str) -> dict[str, str]:
    """Parse the simple KEY=VALUE entries used by Docker Compose .env files."""
    values: dict[str, str] = {}
    if not os.path.exists(env_path):
        return values

    with open(env_path, encoding="utf-8") as env_file:
        for raw_line in env_file:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("export "):
                line = line[len("export ") :].strip()

            if "=" in line:
                key, value = line.split("=", 1)
            elif ":" in line:
                key, value = line.split(":", 1)
            else:
                continue

            key = key.strip()
            value = value.strip()
            if not key:
                continue

            normalized_value = normalize_compose_env_value(value)
            reject_compose_env_control_chars(normalized_value)
            values[key] = normalized_value

    return values


def compose_env_key(line: str) -> str | None:
    """Return the key assigned by a Compose .env line, if any."""
    stripped = line.strip()
    if not stripped or stripped.startswith("#"):
        return None
    if stripped.startswith("export "):
        stripped = stripped[len("export ") :].strip()

    separator_indexes = [
        index for index in (stripped.find("="), stripped.find(":")) if index != -1
    ]
    if not separator_indexes:
        return None
    separator_index = min(separator_indexes)
    key = stripped[:separator_index].strip()
    return key or None


def find_closing_quote(value: str, quote: str) -> int:
    """Return the closing quote index, ignoring escaped quotes."""
    escaped = False
    for index in range(1, len(value)):
        char = value[index]
        if escaped:
            escaped = False
            continue
        if char == "\\":
            escaped = True
            continue
        if char == quote:
            return index
    return -1


def normalize_compose_env_value(value: str) -> str:
    """Normalize one Compose .env value enough for atlas.py preflight checks."""
    value = value.strip()
    if not value:
        return value

    if value[0] in {"'", '"'}:
        quote = value[0]
        closing_quote = find_closing_quote(value, quote)
        if closing_quote != -1:
            trailing = value[closing_quote + 1 :].strip()
            if not trailing or trailing.startswith("#"):
                return value[1:closing_quote]

    comment_index = value.find(" #")
    if comment_index != -1:
        value = value[:comment_index].rstrip()

    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def format_compose_env_value(value: str) -> str:
    """Format a generated value for a Docker Compose .env file."""
    reject_compose_env_control_chars(value)
    if COMPOSE_ENV_BARE_VALUE_RE.fullmatch(value):
        return value
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def reject_compose_env_control_chars(value: str) -> None:
    """Reject literal control characters in Docker Compose .env values."""
    control_char = COMPOSE_ENV_CONTROL_CHAR_RE.search(value)
    if control_char:
        raise ValueError(compose_env_control_char_error(control_char.group(0)))


def compose_env_control_char_error(control_char: str) -> str:
    """Return the Compose .env control-character validation message."""
    return f"Docker Compose .env values must not contain control characters: {control_char!r}"


def persist_compose_env_values(
    docker_dir: str,
    values: dict[str, str],
    announce: Callable[[str], None] | None = print,
    env_filename: str = ".env",
) -> None:
    """Persist values to an owner-only env file, updating existing keys in place."""
    if not values:
        return

    env_path = os.path.join(docker_dir, env_filename)
    if os.path.exists(env_path):
        with open(env_path, encoding="utf-8") as env_file:
            lines = env_file.readlines()
    else:
        lines = [
            "# Generated by Atlas Core atlas.py for local runs.\n",
            "# Values here are local scratch-runtime credentials; rotate freely.\n",
        ]

    written: set[str] = set()
    updated_lines: list[str] = []
    for line in lines:
        key = compose_env_key(line)
        if key in values:
            updated_lines.append(f"{key}={format_compose_env_value(values[key])}\n")
            written.add(key)
        else:
            updated_lines.append(line)

    if updated_lines and updated_lines[-1].strip():
        updated_lines.append("\n")

    for key in sorted(set(values) - written):
        updated_lines.append(f"{key}={format_compose_env_value(values[key])}\n")

    write_compose_env_file(env_path, updated_lines)

    if announce is not None:
        keys = ", ".join(sorted(values))
        announce(f"[INFO] Persisted generated values to {env_path}: {keys}")


def write_compose_env_file(env_path: str, lines: list[str]) -> None:
    """Atomically write a Compose .env file with owner-only permissions."""
    env_dir = os.path.dirname(env_path) or "."
    fd, temp_path = tempfile.mkstemp(prefix=".env.", dir=env_dir, text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as env_file:
            env_file.writelines(lines)
            env_file.flush()
            os.fsync(env_file.fileno())
        try:
            os.chmod(temp_path, 0o600)
        except OSError as exc:
            raise OSError(f"failed to secure temporary Compose env file {temp_path}: {exc}") from exc
        os.replace(temp_path, env_path)
        fsync_directory(env_dir)
    except Exception:
        try:
            os.unlink(temp_path)
        except FileNotFoundError:
            pass
        raise


def fsync_directory(path: str) -> None:
    """Best-effort directory fsync after atomic replace."""
    try:
        dir_fd = os.open(path, os.O_RDONLY)
    except OSError:
        return
    try:
        os.fsync(dir_fd)
    except OSError:
        pass
    finally:
        os.close(dir_fd)


def load_compose_dotenv(
    docker_dir: str,
    environ: MutableMapping[str, str] | None = None,
    announce: Callable[[str], None] | None = print,
) -> list[str]:
    """Load Compose's default .env values without overriding shell variables."""
    target_environ = os.environ if environ is None else environ
    env_path = os.path.join(docker_dir, ".env")
    values = parse_compose_env_file(env_path)
    loaded = []
    for key, value in values.items():
        if key not in target_environ:
            target_environ[key] = value
            loaded.append(key)

    if loaded and announce is not None:
        loaded_keys = ", ".join(sorted(loaded))
        announce(f"[INFO] Loaded Docker Compose defaults from {env_path}: {loaded_keys}")
    return loaded
