// Generated by scripts/generate-package-metadata.mjs. Do not edit.
export const PACKAGE_NAME = "atlas-core";
export const PACKAGE_VERSION = "0.0.0-dev";
export const PACKAGE_IMAGE: string | undefined = undefined;
export const PACKAGE_PLUGIN_CONTRACTS = {
  coreToPluginProtocolMajors: [1],
  pluginToSourceGatewayProtocolMajors: [1],
  atlasProtocolRevision: "sha256:a1c6465a21b2962e7ff955a3ef6f2ac6bfc37ca74de787c7ceb1ae1ee58aca94",
  supportedPackageSchemaMajors: [1],
  supportedInteractions: ["map_area"]
} as const;
