// Generated by scripts/generate-package-metadata.mjs. Do not edit.
export const PACKAGE_NAME = "atlas-core";
export const PACKAGE_VERSION = "0.0.0-dev";
export const PACKAGE_IMAGE: string | undefined = undefined;
export const PACKAGE_PLUGIN_CONTRACTS = {
  coreToPluginProtocolMajors: [1],
  pluginToSourceGatewayProtocolMajors: [1],
  atlasProtocolRevision: "sha256:6cb482d1c7f2344d88c3eff5a828653fd6a52743afb2177b3c44da17fb82b518",
  supportedPackageSchemaMajors: [1],
  supportedInteractions: ["map_area"]
} as const;
