// Generated by scripts/plugins.mjs. Do not edit.
export const PACKAGE_PLUGIN_CATALOG = [
  {
    pluginId: "building_scan",
    displayName: "Building Scan",
    lifecycle: "query_only",
    service: "building-scan-plugin",
    image:
      "ghcr.io/the-drunken-coder/atlas-building-scan@sha256:3bb8c7d7761c71fa1a9fb399b275a26686b2c7d39b9be2a2292797284f2f2b25",
    assets: {
      compose: "compose.yml",
      core_endpoint: "core-endpoint.json",
      source_connector: "source-connector.json"
    }
  }
] as const;
