// Generated by scripts/plugins.mjs. Do not edit.
export const PACKAGE_PLUGIN_CATALOG = [
  {
    pluginId: "building_scan",
    displayName: "Building Scan",
    lifecycle: "query_only",
    service: "building-scan-plugin",
    image:
      "ghcr.io/the-drunken-coder/atlas-building-scan@sha256:35433a7894bc71d73e11d27fd60732aafa405d6c99bfb1edc94c7e499756dbde",
    assets: {
      compose: "compose.yml",
      core_endpoint: "core-endpoint.json",
      source_connector: "source-connector.json"
    }
  }
] as const;
