// Generated by scripts/plugins.mjs. Do not edit.
export const PACKAGE_PLUGIN_CATALOG = [
  {
    pluginId: "building_scan",
    displayName: "Building Scan",
    lifecycle: "query_only",
    service: "building-scan-plugin",
    image: null,
    assets: {
      compose: "compose.yml",
      core_endpoint: "core-endpoint.json",
      source_connector: "source-connector.json"
    }
  }
] as const;
