package artifacts

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

type goIntegerField struct {
	jsonName string
	goName   string
	pointer  bool
}

func goIntegerUnmarshalSource(root string) ([]byte, error) {
	typesDirectory := filepath.Join(root, filepath.Dir(authoredGoTypesPath))
	parsed, err := parseGoContracts(typesDirectory)
	if err != nil {
		return nil, err
	}

	integerFields := make(map[string][]goIntegerField)
	for typeName, fields := range parsed.structs {
		for jsonName, field := range fields {
			switch field.typeName {
			case "int64":
				integerFields[typeName] = append(integerFields[typeName], goIntegerField{jsonName: jsonName, goName: field.name})
			case "*int64":
				integerFields[typeName] = append(integerFields[typeName], goIntegerField{jsonName: jsonName, goName: field.name, pointer: true})
			}
		}
	}

	typeNames := make([]string, 0, len(integerFields))
	for typeName := range integerFields {
		typeNames = append(typeNames, typeName)
		sort.Slice(integerFields[typeName], func(i, j int) bool {
			return integerFields[typeName][i].jsonName < integerFields[typeName][j].jsonName
		})
	}
	sort.Strings(typeNames)

	var builder strings.Builder
	builder.WriteString("// Code generated by go run ./tools/generate; DO NOT EDIT.\n\n")
	builder.WriteString("package atlasprotocol\n\n")
	builder.WriteString("import (\n")
	builder.WriteString("\t\"bytes\"\n")
	builder.WriteString("\t\"encoding/json\"\n")
	builder.WriteString("\t\"fmt\"\n")
	builder.WriteString("\t\"io\"\n")
	builder.WriteString("\t\"math/big\"\n")
	builder.WriteString(")\n\n")
	builder.WriteString("const atlasProtocolMaxSafeInteger int64 = 9007199254740991\n\n")
	builder.WriteString("func atlasProtocolDecodeInt64JSON(raw json.RawMessage) (int64, error) {\n")
	builder.WriteString("\tdecoder := json.NewDecoder(bytes.NewReader(raw))\n")
	builder.WriteString("\tdecoder.UseNumber()\n")
	builder.WriteString("\tvar value any\n")
	builder.WriteString("\tif err := decoder.Decode(&value); err != nil {\n")
	builder.WriteString("\t\treturn 0, err\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tvar trailing any\n")
	builder.WriteString("\tif err := decoder.Decode(&trailing); err != io.EOF {\n")
	builder.WriteString("\t\tif err == nil {\n")
	builder.WriteString("\t\t\treturn 0, fmt.Errorf(\"trailing JSON value\")\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t\treturn 0, err\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tnumber, ok := value.(json.Number)\n")
	builder.WriteString("\tif !ok {\n")
	builder.WriteString("\t\treturn 0, fmt.Errorf(\"expected JSON number\")\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\trational, ok := new(big.Rat).SetString(number.String())\n")
	builder.WriteString("\tif !ok {\n")
	builder.WriteString("\t\treturn 0, fmt.Errorf(\"invalid JSON number %q\", number)\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tif !rational.IsInt() {\n")
	builder.WriteString("\t\treturn 0, fmt.Errorf(\"JSON number %q is not an integer\", number)\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tinteger := rational.Num()\n")
	builder.WriteString("\tif integer.Cmp(big.NewInt(-atlasProtocolMaxSafeInteger)) < 0 || integer.Cmp(big.NewInt(atlasProtocolMaxSafeInteger)) > 0 {\n")
	builder.WriteString("\t\treturn 0, fmt.Errorf(\"JSON integer %q exceeds the safe range\", number)\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\treturn integer.Int64(), nil\n")
	builder.WriteString("}\n\n")
	builder.WriteString("func atlasProtocolDecodeOptionalInt64JSON(raw json.RawMessage) (*int64, error) {\n")
	builder.WriteString("\tif bytes.Equal(bytes.Trim(raw, \" \\t\\r\\n\"), []byte(\"null\")) {\n")
	builder.WriteString("\t\treturn nil, nil\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tvalue, err := atlasProtocolDecodeInt64JSON(raw)\n")
	builder.WriteString("\tif err != nil {\n")
	builder.WriteString("\t\treturn nil, err\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\treturn &value, nil\n")
	builder.WriteString("}\n\n")
	builder.WriteString("func atlasProtocolCanonicalizeIntegerFields(data []byte, optional map[string]bool) (map[string]json.RawMessage, error) {\n")
	builder.WriteString("\tdecoder := json.NewDecoder(bytes.NewReader(data))\n")
	builder.WriteString("\ttoken, err := decoder.Token()\n")
	builder.WriteString("\tif err != nil {\n")
	builder.WriteString("\t\treturn nil, err\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tdelimiter, ok := token.(json.Delim)\n")
	builder.WriteString("\tif !ok || delimiter != '{' {\n")
	builder.WriteString("\t\treturn nil, fmt.Errorf(\"expected JSON object\")\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\traw := make(map[string]json.RawMessage)\n")
	builder.WriteString("\tfor decoder.More() {\n")
	builder.WriteString("\t\ttoken, err := decoder.Token()\n")
	builder.WriteString("\t\tif err != nil {\n")
	builder.WriteString("\t\t\treturn nil, err\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t\tname, ok := token.(string)\n")
	builder.WriteString("\t\tif !ok {\n")
	builder.WriteString("\t\t\treturn nil, fmt.Errorf(\"expected JSON object key\")\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t\tvar rawValue json.RawMessage\n")
	builder.WriteString("\t\tif err := decoder.Decode(&rawValue); err != nil {\n")
	builder.WriteString("\t\t\treturn nil, err\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t\tif isOptional, ok := optional[name]; ok {\n")
	builder.WriteString("\t\t\tvar canonical []byte\n")
	builder.WriteString("\t\t\tif isOptional {\n")
	builder.WriteString("\t\t\t\toptionalValue, optionalErr := atlasProtocolDecodeOptionalInt64JSON(rawValue)\n")
	builder.WriteString("\t\t\t\tif optionalErr != nil {\n")
	builder.WriteString("\t\t\t\t\treturn nil, fmt.Errorf(\"%s: %w\", name, optionalErr)\n")
	builder.WriteString("\t\t\t\t}\n")
	builder.WriteString("\t\t\t\tif optionalValue == nil {\n")
	builder.WriteString("\t\t\t\t\tcanonical = []byte(\"null\")\n")
	builder.WriteString("\t\t\t\t} else {\n")
	builder.WriteString("\t\t\t\t\tcanonical, err = json.Marshal(*optionalValue)\n")
	builder.WriteString("\t\t\t\t}\n")
	builder.WriteString("\t\t\t} else {\n")
	builder.WriteString("\t\t\t\tdecoded, err := atlasProtocolDecodeInt64JSON(rawValue)\n")
	builder.WriteString("\t\t\t\tif err != nil {\n")
	builder.WriteString("\t\t\t\t\treturn nil, fmt.Errorf(\"%s: %w\", name, err)\n")
	builder.WriteString("\t\t\t\t}\n")
	builder.WriteString("\t\t\t\tcanonical, err = json.Marshal(decoded)\n")
	builder.WriteString("\t\t\t}\n")
	builder.WriteString("\t\t\tif err != nil {\n")
	builder.WriteString("\t\t\t\treturn nil, err\n")
	builder.WriteString("\t\t\t}\n")
	builder.WriteString("\t\t\traw[name] = canonical\n")
	builder.WriteString("\t\t\tcontinue\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t\traw[name] = rawValue\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tif token, err := decoder.Token(); err != nil {\n")
	builder.WriteString("\t\treturn nil, err\n")
	builder.WriteString("\t} else if delimiter, ok := token.(json.Delim); !ok || delimiter != '}' {\n")
	builder.WriteString("\t\treturn nil, fmt.Errorf(\"expected end of JSON object\")\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tvar trailing any\n")
	builder.WriteString("\tif err := decoder.Decode(&trailing); err != io.EOF {\n")
	builder.WriteString("\t\tif err == nil {\n")
	builder.WriteString("\t\t\treturn nil, fmt.Errorf(\"trailing JSON value\")\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t\treturn nil, err\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\treturn raw, nil\n")
	builder.WriteString("}\n\n")

	for _, typeName := range typeNames {
		fields := integerFields[typeName]
		builder.WriteString("func (value *")
		builder.WriteString(typeName)
		builder.WriteString(") UnmarshalJSON(data []byte) error {\n")
		builder.WriteString("\tif bytes.Equal(bytes.Trim(data, \" \\t\\r\\n\"), []byte(\"null\")) {\n")
		builder.WriteString("\t\treturn nil\n")
		builder.WriteString("\t}\n")
		builder.WriteString("\ttype alias ")
		builder.WriteString(typeName)
		builder.WriteString("\n")
		builder.WriteString("\traw, err := atlasProtocolCanonicalizeIntegerFields(data, map[string]bool{")
		for _, field := range fields {
			builder.WriteString(fmt.Sprintf("%q: %t, ", field.jsonName, field.pointer))
		}
		builder.WriteString("})\n")
		builder.WriteString("\tif err != nil {\n")
		builder.WriteString("\t\treturn err\n")
		builder.WriteString("\t}\n")
		builder.WriteString("\tcanonical, err := json.Marshal(raw)\n")
		builder.WriteString("\tif err != nil {\n")
		builder.WriteString("\t\treturn err\n")
		builder.WriteString("\t}\n")
		builder.WriteString("\tdecoded := alias(*value)\n")
		builder.WriteString("\tif err := json.Unmarshal(canonical, &decoded); err != nil {\n")
		builder.WriteString("\t\treturn err\n")
		builder.WriteString("\t}\n")
		builder.WriteString("\t*value = ")
		builder.WriteString(typeName)
		builder.WriteString("(decoded)\n")
		builder.WriteString("\treturn nil\n")
		builder.WriteString("}\n\n")
	}

	return formatGeneratedGoSource(builder.String())
}
