package artifacts

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

type goIntegerField struct {
	jsonName string
	goName   string
	pointer  bool
}

func goIntegerUnmarshalSource(root string) ([]byte, error) {
	typesDirectory := filepath.Join(root, filepath.Dir(authoredGoTypesPath))
	parsed, err := parseGoContracts(typesDirectory)
	if err != nil {
		return nil, err
	}
	bundle, err := LoadSchemaBundle(root)
	if err != nil {
		return nil, err
	}
	definitions, err := schemaDefs(bundle)
	if err != nil {
		return nil, err
	}

	integerFields := make(map[string][]goIntegerField)
	for typeName, fields := range parsed.structs {
		for jsonName, field := range fields {
			switch field.typeName {
			case "int64":
				integerFields[typeName] = append(integerFields[typeName], goIntegerField{jsonName: jsonName, goName: field.name})
			case "*int64":
				integerFields[typeName] = append(integerFields[typeName], goIntegerField{jsonName: jsonName, goName: field.name, pointer: true})
			}
		}
	}

	typeNames := make([]string, 0, len(parsed.structs))
	for typeName := range parsed.structs {
		if len(integerFields[typeName]) == 0 && !goTypeContainsJSONValue(typeName, parsed, nil) {
			continue
		}
		typeNames = append(typeNames, typeName)
		sort.Slice(integerFields[typeName], func(i, j int) bool {
			return integerFields[typeName][i].jsonName < integerFields[typeName][j].jsonName
		})
	}
	sort.Strings(typeNames)

	var builder strings.Builder
	builder.WriteString("// Code generated by go run ./tools/generate; DO NOT EDIT.\n\n")
	builder.WriteString("package atlasprotocol\n\n")
	builder.WriteString("import (\n")
	builder.WriteString("\t\"bytes\"\n")
	builder.WriteString("\t\"encoding/json\"\n")
	builder.WriteString("\t\"fmt\"\n")
	builder.WriteString("\t\"io\"\n")
	builder.WriteString("\t\"strconv\"\n")
	builder.WriteString("\t\"strings\"\n")
	builder.WriteString(")\n\n")
	builder.WriteString("const atlasProtocolMaxSafeInteger int64 = 9007199254740991\n\n")
	builder.WriteString("func atlasProtocolDecodeInt64JSON(raw json.RawMessage) (int64, error) {\n")
	builder.WriteString("\tdecoder := json.NewDecoder(bytes.NewReader(raw))\n")
	builder.WriteString("\tdecoder.UseNumber()\n")
	builder.WriteString("\tvar value any\n")
	builder.WriteString("\tif err := decoder.Decode(&value); err != nil {\n")
	builder.WriteString("\t\treturn 0, err\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tvar trailing any\n")
	builder.WriteString("\tif err := decoder.Decode(&trailing); err != io.EOF {\n")
	builder.WriteString("\t\tif err == nil {\n")
	builder.WriteString("\t\t\treturn 0, fmt.Errorf(\"trailing JSON value\")\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t\treturn 0, err\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tnumber, ok := value.(json.Number)\n")
	builder.WriteString("\tif !ok {\n")
	builder.WriteString("\t\treturn 0, fmt.Errorf(\"expected JSON number\")\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\treturn atlasProtocolParseSafeInteger(number.String())\n")
	builder.WriteString("}\n\n")
	builder.WriteString("func atlasProtocolParseSafeInteger(number string) (int64, error) {\n")
	builder.WriteString("\tnegative := strings.HasPrefix(number, \"-\")\n")
	builder.WriteString("\tunsigned := strings.TrimPrefix(number, \"-\")\n")
	builder.WriteString("\tmantissa := unsigned\n")
	builder.WriteString("\texponent := 0\n")
	builder.WriteString("\tif index := strings.IndexAny(unsigned, \"eE\"); index >= 0 {\n")
	builder.WriteString("\t\tmantissa = unsigned[:index]\n")
	builder.WriteString("\t\tparsed, err := atlasProtocolParseBoundedExponent(unsigned[index+1:], len(unsigned)+32)\n")
	builder.WriteString("\t\tif err != nil {\n")
	builder.WriteString("\t\t\treturn 0, fmt.Errorf(\"invalid JSON number %q\", number)\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t\texponent = parsed\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tfractionDigits := 0\n")
	builder.WriteString("\tdigits := mantissa\n")
	builder.WriteString("\tif index := strings.IndexByte(mantissa, '.'); index >= 0 {\n")
	builder.WriteString("\t\tfractionDigits = len(mantissa) - index - 1\n")
	builder.WriteString("\t\tdigits = mantissa[:index] + mantissa[index+1:]\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tdigits = strings.TrimLeft(digits, \"0\")\n")
	builder.WriteString("\tif digits == \"\" {\n")
	builder.WriteString("\t\treturn 0, nil\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tscale := exponent - fractionDigits\n")
	builder.WriteString("\tif scale < 0 {\n")
	builder.WriteString("\t\tremove := -scale\n")
	builder.WriteString("\t\tif remove >= len(digits) || len(digits)-len(strings.TrimRight(digits, \"0\")) < remove {\n")
	builder.WriteString("\t\t\treturn 0, fmt.Errorf(\"JSON number %q is not an integer\", number)\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t\tdigits = digits[:len(digits)-remove]\n")
	builder.WriteString("\t} else if scale > 0 {\n")
	builder.WriteString("\t\tif len(digits)+scale > 16 {\n")
	builder.WriteString("\t\t\treturn 0, fmt.Errorf(\"JSON integer %q exceeds the safe range\", number)\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t\tdigits += strings.Repeat(\"0\", scale)\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tif len(digits) > 16 {\n")
	builder.WriteString("\t\treturn 0, fmt.Errorf(\"JSON integer %q exceeds the safe range\", number)\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tmagnitude, err := strconv.ParseInt(digits, 10, 64)\n")
	builder.WriteString("\tif err != nil || magnitude > atlasProtocolMaxSafeInteger {\n")
	builder.WriteString("\t\treturn 0, fmt.Errorf(\"JSON integer %q exceeds the safe range\", number)\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tif negative {\n")
	builder.WriteString("\t\treturn -magnitude, nil\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\treturn magnitude, nil\n")
	builder.WriteString("}\n\n")
	builder.WriteString("func atlasProtocolParseBoundedExponent(text string, limit int) (int, error) {\n")
	builder.WriteString("\tnegative := strings.HasPrefix(text, \"-\")\n")
	builder.WriteString("\tdigits := strings.TrimPrefix(strings.TrimPrefix(text, \"-\"), \"+\")\n")
	builder.WriteString("\tif digits == \"\" {\n")
	builder.WriteString("\t\treturn 0, fmt.Errorf(\"missing exponent\")\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tvalue := 0\n")
	builder.WriteString("\tfor _, digit := range digits {\n")
	builder.WriteString("\t\tif digit < '0' || digit > '9' {\n")
	builder.WriteString("\t\t\treturn 0, fmt.Errorf(\"invalid exponent\")\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t\tif value < limit {\n")
	builder.WriteString("\t\t\tvalue = min(limit, value*10+int(digit-'0'))\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tif negative {\n")
	builder.WriteString("\t\treturn -value, nil\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\treturn value, nil\n")
	builder.WriteString("}\n\n")
	builder.WriteString("func atlasProtocolDecodeOptionalInt64JSON(raw json.RawMessage) (*int64, error) {\n")
	builder.WriteString("\tif bytes.Equal(bytes.Trim(raw, \" \\t\\r\\n\"), []byte(\"null\")) {\n")
	builder.WriteString("\t\treturn nil, nil\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tvalue, err := atlasProtocolDecodeInt64JSON(raw)\n")
	builder.WriteString("\tif err != nil {\n")
	builder.WriteString("\t\treturn nil, err\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\treturn &value, nil\n")
	builder.WriteString("}\n\n")
	builder.WriteString("func atlasProtocolCanonicalizeIntegerFields(data []byte, allowed map[string]struct{}, optional map[string]bool) (map[string]json.RawMessage, error) {\n")
	builder.WriteString("\tdecoder := json.NewDecoder(bytes.NewReader(data))\n")
	builder.WriteString("\ttoken, err := decoder.Token()\n")
	builder.WriteString("\tif err != nil {\n")
	builder.WriteString("\t\treturn nil, err\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tdelimiter, ok := token.(json.Delim)\n")
	builder.WriteString("\tif !ok || delimiter != '{' {\n")
	builder.WriteString("\t\treturn nil, fmt.Errorf(\"expected JSON object\")\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\traw := make(map[string]json.RawMessage)\n")
	builder.WriteString("\tfor decoder.More() {\n")
	builder.WriteString("\t\ttoken, err := decoder.Token()\n")
	builder.WriteString("\t\tif err != nil {\n")
	builder.WriteString("\t\t\treturn nil, err\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t\tname, ok := token.(string)\n")
	builder.WriteString("\t\tif !ok {\n")
	builder.WriteString("\t\t\treturn nil, fmt.Errorf(\"expected JSON object key\")\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t\tif _, ok := allowed[name]; !ok {\n")
	builder.WriteString("\t\t\treturn nil, fmt.Errorf(\"unknown field %q\", name)\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t\tvar rawValue json.RawMessage\n")
	builder.WriteString("\t\tif err := decoder.Decode(&rawValue); err != nil {\n")
	builder.WriteString("\t\t\treturn nil, err\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t\tif isOptional, ok := optional[name]; ok {\n")
	builder.WriteString("\t\t\tvar canonical []byte\n")
	builder.WriteString("\t\t\tif isOptional {\n")
	builder.WriteString("\t\t\t\toptionalValue, optionalErr := atlasProtocolDecodeOptionalInt64JSON(rawValue)\n")
	builder.WriteString("\t\t\t\tif optionalErr != nil {\n")
	builder.WriteString("\t\t\t\t\treturn nil, fmt.Errorf(\"%s: %w\", name, optionalErr)\n")
	builder.WriteString("\t\t\t\t}\n")
	builder.WriteString("\t\t\t\tif optionalValue == nil {\n")
	builder.WriteString("\t\t\t\t\tcanonical = []byte(\"null\")\n")
	builder.WriteString("\t\t\t\t} else {\n")
	builder.WriteString("\t\t\t\t\tcanonical = strconv.AppendInt(nil, *optionalValue, 10)\n")
	builder.WriteString("\t\t\t\t}\n")
	builder.WriteString("\t\t\t} else {\n")
	builder.WriteString("\t\t\t\tdecoded, err := atlasProtocolDecodeInt64JSON(rawValue)\n")
	builder.WriteString("\t\t\t\tif err != nil {\n")
	builder.WriteString("\t\t\t\t\treturn nil, fmt.Errorf(\"%s: %w\", name, err)\n")
	builder.WriteString("\t\t\t\t}\n")
	builder.WriteString("\t\t\t\tcanonical = strconv.AppendInt(nil, decoded, 10)\n")
	builder.WriteString("\t\t\t}\n")
	builder.WriteString("\t\t\traw[name] = canonical\n")
	builder.WriteString("\t\t\tcontinue\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t\traw[name] = rawValue\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tif token, err := decoder.Token(); err != nil {\n")
	builder.WriteString("\t\treturn nil, err\n")
	builder.WriteString("\t} else if delimiter, ok := token.(json.Delim); !ok || delimiter != '}' {\n")
	builder.WriteString("\t\treturn nil, fmt.Errorf(\"expected end of JSON object\")\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\tvar trailing any\n")
	builder.WriteString("\tif err := decoder.Decode(&trailing); err != io.EOF {\n")
	builder.WriteString("\t\tif err == nil {\n")
	builder.WriteString("\t\t\treturn nil, fmt.Errorf(\"trailing JSON value\")\n")
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t\treturn nil, err\n")
	builder.WriteString("\t}\n")
	builder.WriteString("\treturn raw, nil\n")
	builder.WriteString("}\n\n")
	builder.WriteString("func atlasProtocolDecodeCanonicalJSON(data []byte, target any) error {\n")
	builder.WriteString("\tdecoder := json.NewDecoder(bytes.NewReader(data))\n")
	builder.WriteString("\tdecoder.UseNumber()\n")
	builder.WriteString("\treturn decoder.Decode(target)\n")
	builder.WriteString("}\n\n")

	for _, typeName := range typeNames {
		fields := integerFields[typeName]
		allowed := parsed.structs[typeName]
		if definition, ok := definitions[typeName].(map[string]any); ok {
			if properties, ok := definition["properties"].(map[string]any); ok {
				allowedFields := make(map[string]goField, len(properties))
				for jsonName := range properties {
					allowedFields[jsonName] = goField{}
				}
				allowed = allowedFields
			}
		}
		allowedFields := make([]string, 0, len(allowed))
		for jsonName := range allowed {
			allowedFields = append(allowedFields, jsonName)
		}
		sort.Strings(allowedFields)
		builder.WriteString("func (value *")
		builder.WriteString(typeName)
		builder.WriteString(") UnmarshalJSON(data []byte) error {\n")
		builder.WriteString("\tif bytes.Equal(bytes.Trim(data, \" \\t\\r\\n\"), []byte(\"null\")) {\n")
		builder.WriteString("\t\treturn nil\n")
		builder.WriteString("\t}\n")
		builder.WriteString("\ttype alias ")
		builder.WriteString(typeName)
		builder.WriteString("\n")
		if len(fields) == 0 {
			builder.WriteString("\tdecoded := alias(*value)\n")
			builder.WriteString("\tif err := atlasProtocolDecodeCanonicalJSON(data, &decoded); err != nil {\n")
			builder.WriteString("\t\treturn err\n")
			builder.WriteString("\t}\n")
			builder.WriteString("\t*value = ")
			builder.WriteString(typeName)
			builder.WriteString("(decoded)\n")
			builder.WriteString("\treturn nil\n")
			builder.WriteString("}\n\n")
			continue
		}
		builder.WriteString("\traw, err := atlasProtocolCanonicalizeIntegerFields(data, map[string]struct{}{")
		for _, jsonName := range allowedFields {
			fmt.Fprintf(&builder, "%q: {}, ", jsonName)
		}
		builder.WriteString("}, map[string]bool{")
		for _, field := range fields {
			fmt.Fprintf(&builder, "%q: %t, ", field.jsonName, field.pointer)
		}
		builder.WriteString("})\n")
		builder.WriteString("\tif err != nil {\n")
		builder.WriteString("\t\treturn err\n")
		builder.WriteString("\t}\n")
		builder.WriteString("\tcanonical, err := json.Marshal(raw)\n")
		builder.WriteString("\tif err != nil {\n")
		builder.WriteString("\t\treturn err\n")
		builder.WriteString("\t}\n")
		builder.WriteString("\tdecoded := alias(*value)\n")
		builder.WriteString("\tif err := atlasProtocolDecodeCanonicalJSON(canonical, &decoded); err != nil {\n")
		builder.WriteString("\t\treturn err\n")
		builder.WriteString("\t}\n")
		builder.WriteString("\t*value = ")
		builder.WriteString(typeName)
		builder.WriteString("(decoded)\n")
		builder.WriteString("\treturn nil\n")
		builder.WriteString("}\n\n")
	}

	return formatGeneratedGoSource(builder.String())
}

func goTypeContainsJSONValue(typeName string, parsed parsedGoContracts, visiting map[string]bool) bool {
	if typeName == "JSONValue" || strings.Contains(typeName, "JSONValue") {
		return true
	}
	if strings.HasPrefix(typeName, "*") {
		return goTypeContainsJSONValue(typeName[1:], parsed, visiting)
	}
	if strings.HasPrefix(typeName, "[]") {
		return goTypeContainsJSONValue(typeName[2:], parsed, visiting)
	}
	if strings.HasPrefix(typeName, "map[") {
		if closingBracket := strings.IndexByte(typeName, ']'); closingBracket >= 0 {
			return goTypeContainsJSONValue(typeName[closingBracket+1:], parsed, visiting)
		}
		return false
	}
	if alias, ok := parsed.aliases[typeName]; ok {
		return goTypeContainsJSONValue(alias, parsed, visiting)
	}
	fields, ok := parsed.structs[typeName]
	if !ok {
		return false
	}
	if visiting == nil {
		visiting = make(map[string]bool)
	}
	if visiting[typeName] {
		return false
	}
	visiting[typeName] = true
	defer delete(visiting, typeName)
	for _, field := range fields {
		if goTypeContainsJSONValue(field.typeName, parsed, visiting) {
			return true
		}
	}
	return false
}
