package artifacts

import (
	"fmt"
	"strconv"
	"strings"
)

// publicGoValidatorDefinitions is the deliberate generated Go facade. Schema
// helpers do not become public validators merely by appearing in $defs.
var publicGoValidatorDefinitions = []string{
	"EntityBlob",
	"ObjectBlob",
	"EntityResource",
	"TaskResource",
	"ObjectResource",
	"ObjectDetailResource",
	"ErrorResponse",
	"ProtocolRevisionResponse",
	"EntityCheckInRequest",
	"EntityCheckInFullResponse",
	"EntityCheckInMinimalResponse",
	"EntityCheckInResponse",
	"FullDatasetResponse",
	"ChangedSinceResponse",
	"EntityCreateRequest",
	"EntityUpdateRequest",
	"TaskCreateRequest",
	"TaskAcknowledgeRequest",
	"TaskStartRequest",
	"TaskProgressRequest",
	"TaskCompleteRequest",
	"TaskFailRequest",
	"TaskCancelRequest",
	"RuntimeRegistrationRequest",
	"RuntimeStopRequest",
	"RuntimeReadyRequest",
	"RuntimeTaskDeliveryResponse",
	"ObjectCreateRequest",
	"ObjectUpdateRequest",
	"FeedEvent",
	"FeedAuthMessage",
	"FeedSubscribeMessage",
	"FeedUnsubscribeMessage",
	"FeedClientMessage",
	"FeedHandshakeMessage",
	"FeedSubscriptionBarrierMessage",
	"FeedSubscriptionsReadyMessage",
	"EntityComponents",
	"CustomPluginComponent",
	"CommandCatalog",
	"CommandManifest",
	"CommandManifestEntry",
	"PluginManifest",
	"PluginStatus",
	"PluginDiscoveryResponse",
	"MediaRefsComponent",
	"MilViewComponent",
	"HealthComponent",
	"SensorRefsComponent",
	"CommunicationsComponent",
	"StatusComponent",
	"HeartbeatComponent",
	"TelemetryComponent",
	"GeometryComponent",
}

func goValidatorsSource(defs map[string]any) ([]byte, error) {
	var builder strings.Builder
	builder.WriteString("// Code generated by go run ./tools/generate; DO NOT EDIT.\n\n")
	builder.WriteString("package atlasprotocol\n\n")
	builder.WriteString("import \"github.com/the-drunken-coder/atlas/packages/protocol/validator\"\n\n")
	seen := make(map[string]struct{}, len(publicGoValidatorDefinitions))
	for i, definition := range publicGoValidatorDefinitions {
		if _, duplicate := seen[definition]; duplicate {
			return nil, fmt.Errorf("public Go validator definition %s is duplicated", definition)
		}
		seen[definition] = struct{}{}
		if _, ok := defs[definition]; !ok {
			return nil, fmt.Errorf("public Go validator definition %s not found", definition)
		}
		if i > 0 {
			builder.WriteString("\n")
		}
		builder.WriteString("func Validate")
		builder.WriteString(definition)
		builder.WriteString("(value any) []string {\n\treturn validator.ValidateDefinition(")
		builder.WriteString(strconv.Quote(definition))
		builder.WriteString(", value)\n}\n")
	}
	return formatGeneratedGoSource(builder.String())
}
