package artifacts

import (
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strings"
)

type typeScriptSchema map[string]any

func typeScriptSource(revision string, schemas map[string][]byte) ([]byte, error) {
	revision, err := validateProtocolRevision(revision)
	if err != nil {
		return nil, err
	}
	gen := &typeScriptGenerator{
		defs: make(map[string]typeScriptSchema),
	}
	names := make([]string, 0, len(schemas))
	for name := range schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		var root typeScriptSchema
		if err := json.Unmarshal(schemas[name], &root); err != nil {
			return nil, fmt.Errorf("parse %s schema for TypeScript: %w", name, err)
		}
		if err := gen.collectDefs(root); err != nil {
			return nil, err
		}
		if err := gen.addDef(name, stripSchemaMetadata(root)); err != nil {
			return nil, err
		}
	}

	var builder strings.Builder
	builder.WriteString("// Code generated by go run ./tools/generate; DO NOT EDIT.\n\n")
	builder.WriteString("export const ATLAS_PROTOCOL_REVISION = ")
	builder.WriteString(jsonString(revision))
	builder.WriteString(" as const;\n")
	builder.WriteString("export type AtlasProtocolRevision = typeof ATLAS_PROTOCOL_REVISION;\n\n")
	builder.WriteString("type RequireAtLeastOne<T, Keys extends keyof T = keyof T> = Keys extends keyof T ? Required<Pick<T, Keys>> & Partial<Omit<T, Keys>> : never;\n\n")

	defNames := make([]string, 0, len(gen.defs))
	for name := range gen.defs {
		defNames = append(defNames, name)
	}
	sort.Strings(defNames)
	for _, name := range defNames {
		builder.WriteString("export type ")
		builder.WriteString(name)
		builder.WriteString(" = ")
		builder.WriteString(gen.typeFor(gen.defs[name], name, 0))
		builder.WriteString(";\n\n")
	}
	resourceTypeValues, err := resourceTypeValuesSource(gen)
	if err != nil {
		return nil, err
	}
	builder.WriteString(resourceTypeValues)
	validatorSource, err := runtimeValidatorSource(gen)
	if err != nil {
		return nil, err
	}
	builder.WriteString(validatorSource)
	return formatTypeScript([]byte(builder.String())), nil
}

type typeScriptGenerator struct {
	defs map[string]typeScriptSchema
}

func (g *typeScriptGenerator) collectDefs(root typeScriptSchema) error {
	rawDefs, ok := root["$defs"].(map[string]any)
	if !ok {
		return nil
	}
	keys := make([]string, 0, len(rawDefs))
	for key := range rawDefs {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		schema, ok := rawDefs[key].(map[string]any)
		if !ok {
			continue
		}
		name := typeName(key)
		if isSelfRefType(name, schema) {
			continue
		}
		if err := g.addDef(name, schema); err != nil {
			return err
		}
	}
	return nil
}

func (g *typeScriptGenerator) addDef(name string, schema typeScriptSchema) error {
	if existing, exists := g.defs[name]; exists {
		if reflect.DeepEqual(existing, schema) {
			return nil
		}
		if isSelfRefType(name, existing) {
			g.defs[name] = schema
			return nil
		}
		return fmt.Errorf("typescript type name collision for %q: existing=%s new=%s", name, summarizeTypeScriptSchema(existing), summarizeTypeScriptSchema(schema))
	}
	g.defs[name] = schema
	return nil
}

func summarizeTypeScriptSchema(schema typeScriptSchema) string {
	keys := make([]string, 0, len(schema))
	for key := range schema {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	parts := make([]string, 0, 3)
	if typ, ok := schema["type"].(string); ok {
		parts = append(parts, "type="+typ)
	}
	if ref, ok := schema["$ref"].(string); ok {
		parts = append(parts, "ref="+ref)
	}
	parts = append(parts, "keys="+strings.Join(keys, ","))
	return strings.Join(parts, " ")
}

func stripSchemaMetadata(root typeScriptSchema) typeScriptSchema {
	out := make(typeScriptSchema, len(root))
	for key, value := range root {
		switch key {
		case "$schema", "$comment", "$defs", "x-atlas-protocol-revision":
			continue
		default:
			out[key] = value
		}
	}
	return out
}

func isSelfRefType(name string, schema typeScriptSchema) bool {
	ref, ok := schema["$ref"].(string)
	return ok && typeNameFromRef(ref) == name
}
